function afDate(ts){if(!ts)return'—';try{return new Date(Number(ts)).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}catch{return'—'}}
function afOk(t){return !t?.status||t.status==='complete'}
function afRows(){return [...(S.tx||[])].filter(afOk).sort((a,b)=>Number(b?.created||0)-Number(a?.created||0))}
function afBid(t){return Number(t?.settings?.waiver_bid||t?.settings?.bid||0)||0}
function afTeamIds(t){const ids=new Set([...(t?.roster_ids||[]),...Object.values(t?.adds||{}),...Object.values(t?.drops||{})].map(Number).filter(Boolean));return [...ids]}
function afPlayerIds(t){return [...new Set([...Object.keys(t?.adds||{}),...Object.keys(t?.drops||{})])]}
function afType(t){if(t?.type==='trade')return'Trade';if(t?.type==='waiver')return'Waiver';if(t?.type==='free_agent')return'Free Agent';return String(t?.type||'Transaction').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}
function afSummary(t){const adds=Object.entries(t?.adds||{}),drops=Object.entries(t?.drops||{}),parts=[];if(t?.type==='trade'){afTeamIds(t).forEach(rid=>{const got=adds.filter(([,to])=>Number(to)===Number(rid)).map(([id])=>pname(String(id)));if(got.length)parts.push(`${name(roster(rid))} received ${got.join(', ')}`)});const pc=(t?.draft_picks||[]).length;if(pc)parts.push(`${pc} draft pick${pc===1?'':'s'} moved`)}else{adds.forEach(([id,rid])=>parts.push(`${name(roster(Number(rid)))} added ${pname(String(id))}`));drops.forEach(([id,rid])=>parts.push(`${name(roster(Number(rid)))} dropped ${pname(String(id))}`));const bid=afBid(t);if(bid)parts.push(`FAAB $${bid}`)}return parts.join(' · ')||'League transaction'}
function afRecent(){const rows=afRows().slice(0,75);if(!rows.length)return'<div class="card muted">No current-season transactions have been returned from Sleeper yet.</div>';return `<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">LEAGUE TRANSACTION FEED</div><h2>Recent Activity</h2></div><p class="muted">Trades, waivers, free-agent adds and drops from Sleeper.</p></div><div class="activity-feed">${rows.map(t=>`<div class="card activity-item"><div class="activity-icon">${t.type==='trade'?'⇄':t.type==='waiver'?'＋':t.type==='free_agent'?'↗':'•'}</div><div class="grow"><div class="activity-top"><strong>${esc(afType(t))}</strong><span>${afDate(t.created)}</span></div><p>${esc(afSummary(t))}</p><div class="activity-links">${afPlayerIds(t).slice(0,4).map(id=>`<button onclick="openPlayer('${esc(id)}','activity')">${esc(pname(id))} →</button>`).join('')}${afTeamIds(t).slice(0,3).map(rid=>`<button onclick="openTeam(${rid})">${esc(name(roster(rid)))}</button>`).join('')}</div></div></div>`).join('')}</div></div>`}
function afWaivers(){const rows=afRows().filter(t=>t.type==='waiver'||t.type==='free_agent'),claims=rows.filter(t=>t.type==='waiver').length,fas=rows.filter(t=>t.type==='free_agent').length,spent=rows.reduce((s,t)=>s+afBid(t),0);return `<div class="section-panel"><div class="grid grid-3 section-summary">${card('Waiver Claims',claims,'Completed claims')}${card('Free-Agent Adds',fas,'Immediate adds')}${card('FAAB Spent',`$${spent}`,'Recorded bids')}</div>${rows.length?`<div class="card table-wrap"><table class="table"><thead><tr><th>Date</th><th>Team</th><th>Added</th><th>Dropped</th><th>FAAB</th></tr></thead><tbody>${rows.map(t=>{const add=Object.entries(t.adds||{})[0],drop=Object.entries(t.drops||{})[0],rid=Number(add?.[1]||drop?.[1]||t.roster_ids?.[0]||0);return `<tr><td>${afDate(t.created)}</td><td>${esc(name(roster(rid)))}</td><td>${add?esc(pname(String(add[0]))):'—'}</td><td>${drop?esc(pname(String(drop[0]))):'—'}</td><td>${afBid(t)?`$${afBid(t)}`:'—'}</td></tr>`}).join('')}</tbody></table></div>`:'<div class="card muted">No waiver or free-agent activity yet.</div>'}</div>`}
function afTrades(){const rows=afRows().filter(t=>t.type==='trade');if(!rows.length)return'<div class="card muted">No completed trades yet this season.</div>';return `<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">DEAL FLOW</div><h2>Trade Activity</h2></div></div><div class="activity-feed">${rows.map(t=>`<div class="card activity-item"><div class="activity-icon">⇄</div><div class="grow"><div class="activity-top"><strong>${afDate(t.created)}</strong><span>${afPlayerIds(t).length} players</span></div><p>${esc(afSummary(t))}</p><div class="activity-links">${afTeamIds(t).map(rid=>`<button onclick="openTeam(${rid})">${esc(name(roster(rid)))}</button>`).join('')}</div></div></div>`).join('')}</div></div>`}
function afManagers(){const map=new Map((S.rosters||[]).map(r=>[Number(r.roster_id),{r,total:0,trades:0,waivers:0,adds:0,drops:0,faab:0}]));afRows().forEach(t=>afTeamIds(t).forEach(rid=>{const x=map.get(Number(rid));if(!x)return;x.total++;if(t.type==='trade')x.trades++;if(t.type==='waiver')x.waivers++;x.adds+=Object.values(t.adds||{}).filter(v=>Number(v)===Number(rid)).length;x.drops+=Object.values(t.drops||{}).filter(v=>Number(v)===Number(rid)).length;if(t.type==='waiver'||t.type==='free_agent')x.faab+=afBid(t)}));const rows=[...map.values()].sort((a,b)=>b.total-a.total||b.trades-a.trades);return `<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">OWNER BEHAVIOR</div><h2>Manager Activity</h2></div></div><div class="card table-wrap"><table class="table"><thead><tr><th>#</th><th>Franchise</th><th>Total</th><th>Trades</th><th>Waivers</th><th>Adds</th><th>Drops</th><th>FAAB</th></tr></thead><tbody>${rows.map((x,i)=>`<tr class="clickable" onclick="openTeam(${x.r.roster_id})"><td class="rank">${i+1}</td><td><strong>${esc(name(x.r))}</strong></td><td>${x.total}</td><td>${x.trades}</td><td>${x.waivers}</td><td>${x.adds}</td><td>${x.drops}</td><td>${x.faab?`$${x.faab}`:'—'}</td></tr>`).join('')}</tbody></table></div></div>`}
function afMilestones(){try{if(typeof storyMilestonesPanel==='function')return storyMilestonesPanel()}catch(e){console.warn('Milestones unavailable',e)}return'<div class="card muted">Milestones will appear as the season builds more history.</div>'}
activityView=function(){const rows=afRows(),waivers=rows.filter(t=>t.type==='waiver').length,trades=rows.filter(t=>t.type==='trade').length,fa=rows.filter(t=>t.type==='free_agent').length;const tabs=[{id:'recent',label:'Recent Activity'},{id:'milestones',label:'Milestones'},{id:'waivers',label:'Waiver / FAAB'},{id:'trades',label:'Trade Activity'},{id:'managers',label:'Manager Activity'}];let panel=activityTab==='milestones'?afMilestones():activityTab==='waivers'?afWaivers():activityTab==='trades'?afTrades():activityTab==='managers'?afManagers():afRecent();return `<div class="grid grid-4 section-summary">${card('Transactions',rows.length,'Current season')}${card('Trades',trades,'Completed')}${card('Waivers',waivers,'Claims')}${card('Free Agents',fa,'Immediate adds')}</div>${innerNav(tabs,activityTab,'setActivityTab')}${panel}`};
window.activityView=activityView;
