let activityTab='recent';
function setActivityTab(id){activityTab=id;render();window.scrollTo({top:0,behavior:'smooth'})}
window.setActivityTab=setActivityTab;
function txStatusOk(t){return !t.status||t.status==='complete'}
function txBid(t){return Number(t.settings?.waiver_bid||t.settings?.bid||0)||0}
function txTeams(t){const ids=new Set([...(t.roster_ids||[]),...Object.values(t.adds||{}),...Object.values(t.drops||{})].map(Number).filter(Boolean));return[...ids]}
function txPlayers(t){const ids=new Set([...Object.keys(t.adds||{}),...Object.keys(t.drops||{})]);return[...ids]}
function txTypeLabel(t){if(t.type==='trade')return'Trade';if(t.type==='waiver')return'Waiver';if(t.type==='free_agent')return'Free Agent';return String(t.type||'Transaction').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}
function txIcon(t){return t.type==='trade'?'⇄':t.type==='waiver'?'＋':t.type==='free_agent'?'↗':'•'}
function activityRows(){return(S.tx||[]).filter(txStatusOk).sort((a,b)=>Number(b.created||0)-Number(a.created||0))}
function txSummary(t){const adds=Object.entries(t.adds||{}),drops=Object.entries(t.drops||{}),parts=[];if(t.type==='trade'){txTeams(t).forEach(rid=>{const received=adds.filter(([,r])=>Number(r)===rid).map(([id])=>pname(id));if(received.length)parts.push(`${name(roster(rid))} received ${received.join(', ')}`)});const picks=(t.draft_picks||[]).length;if(picks)parts.push(`${picks} draft pick${picks===1?'':'s'} moved`)}else{adds.forEach(([id,rid])=>parts.push(`${name(roster(rid))} added ${pname(id)}`));drops.forEach(([id,rid])=>parts.push(`${name(roster(rid))} dropped ${pname(id)}`));const bid=txBid(t);if(bid)parts.push(`FAAB $${bid}`)}return parts.join(' · ')||'League transaction'}
function recentPanel(){const rows=activityRows().slice(0,60);if(!rows.length)return'<div class="card muted">No current-season transactions have been returned from Sleeper yet.</div>';return `<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">LEAGUE TRANSACTION FEED</div><h2>Recent Activity</h2></div><p class="muted">Trades, waivers, free-agent adds and drops from the current Sleeper season.</p></div><div class="activity-feed">${rows.map(t=>`<div class="card activity-item"><div class="activity-icon">${txIcon(t)}</div><div class="grow"><div class="activity-top"><strong>${esc(txTypeLabel(t))}</strong><span>${date(t.created)}</span></div><p>${esc(txSummary(t))}</p><div class="activity-links">${txPlayers(t).slice(0,4).map(id=>`<button onclick="openPlayer('${id}','activity')">${esc(pname(id))} →</button>`).join('')}${txTeams(t).slice(0,3).map(rid=>`<button onclick="openTeam(${rid})">${esc(name(roster(rid)))}</button>`).join('')}</div></div></div>`).join('')}</div></div>`}
function waiverRows(){return activityRows().filter(t=>t.type==='waiver'||t.type==='free_agent')}
function waiverPanel(){const rows=waiverRows();const spent=rows.reduce((s,t)=>s+txBid(t),0),claims=rows.filter(t=>t.type==='waiver').length,fas=rows.filter(t=>t.type==='free_agent').length;return `<div class="section-panel"><div class="grid grid-3 section-summary">${card('Waiver Claims',claims,'Completed claims')}${card('Free-Agent Adds',fas,'Immediate adds')}${card('FAAB Spent',`$${spent}`,'Recorded winning bids')}</div><div class="panel-heading"><div><div class="eyebrow">WAIVER WIRE LEDGER</div><h2>Claims & FAAB</h2></div></div>${rows.length?`<div class="card table-wrap"><table class="table"><thead><tr><th>Date</th><th>Team</th><th>Player Added</th><th>Dropped</th><th>FAAB</th></tr></thead><tbody>${rows.map(t=>{const add=Object.entries(t.adds||{})[0],drop=Object.entries(t.drops||{})[0],rid=Number(add?.[1]||drop?.[1]||t.roster_ids?.[0]);return `<tr><td>${date(t.created)}</td><td><button class="activity-table-link" onclick="openTeam(${rid})">${esc(name(roster(rid)))}</button></td><td>${add?`<button class="activity-table-link" onclick="openPlayer('${add[0]}','activity')">${esc(pname(add[0]))}</button>`:'—'}</td><td>${drop?`<button class="activity-table-link" onclick="openPlayer('${drop[0]}','activity')">${esc(pname(drop[0]))}</button>`:'—'}</td><td>${txBid(t)?`$${txBid(t)}`:'—'}</td></tr>`}).join('')}</tbody></table></div>`:'<div class="card muted">No waiver or free-agent transactions yet.</div>'}</div>`}
function tradeActivityPanel(){const rows=activityRows().filter(t=>t.type==='trade');return `<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">DEAL FLOW</div><h2>Trade Activity</h2></div><p class="muted">A quick transaction-level view. Use Trade Center for detailed value analysis.</p></div>${rows.length?`<div class="activity-feed">${rows.map(t=>{const players=txPlayers(t),value=players.reduce((s,id)=>s+dynastyValue(id),0);return `<div class="card activity-item trade-activity-item"><div class="activity-icon">⇄</div><div class="grow"><div class="activity-top"><strong>${date(t.created)}</strong><span>${players.length} players · ${fmt(value)} current player value</span></div><p>${esc(txSummary(t))}</p><div class="activity-links">${txTeams(t).map(rid=>`<button onclick="openTeam(${rid})">${esc(name(roster(rid)))}</button>`).join('')}</div></div><button class="open-trade-center" onclick="go('trades')">Trade Center →</button></div>`}).join('')}</div>`:'<div class="card muted">No completed trades yet this season.</div>'}</div>`}
function managerActivity(){const map=new Map(S.rosters.map(r=>[Number(r.roster_id),{r,adds:0,drops:0,waivers:0,trades:0,faab:0,total:0}]));activityRows().forEach(t=>{const teams=txTeams(t);teams.forEach(rid=>{const x=map.get(Number(rid));if(!x)return;x.total++;if(t.type==='trade')x.trades++;if(t.type==='waiver')x.waivers++;if(t.type==='waiver'||t.type==='free_agent'){x.adds+=Object.values(t.adds||{}).filter(v=>Number(v)===Number(rid)).length;x.drops+=Object.values(t.drops||{}).filter(v=>Number(v)===Number(rid)).length;x.faab+=txBid(t)}})});return[...map.values()].sort((a,b)=>b.total-a.total||b.trades-a.trades||b.waivers-a.waivers)}
function managerPanel(){const rows=managerActivity(),leader=rows[0];return `<div class="section-panel"><div class="grid grid-3 section-summary">${card('Most Active',leader?name(leader.r):'—',leader?`${leader.total} transactions`:'')}${card('Most Trades',rows.length?name([...rows].sort((a,b)=>b.trades-a.trades)[0].r):'—',rows.length?`${Math.max(...rows.map(x=>x.trades))} trades`:'')}${card('Most FAAB Spent',rows.length?name([...rows].sort((a,b)=>b.faab-a.faab)[0].r):'—',rows.length?`$${Math.max(...rows.map(x=>x.faab))}`:'')}</div><div class="panel-heading"><div><div class="eyebrow">OWNER BEHAVIOR</div><h2>Manager Activity</h2></div></div><div class="card table-wrap"><table class="table"><thead><tr><th>#</th><th>Franchise</th><th>Total Tx</th><th>Trades</th><th>Waivers</th><th>Adds</th><th>Drops</th><th>FAAB</th></tr></thead><tbody>${rows.map((x,i)=>`<tr class="clickable" onclick="openTeam(${x.r.roster_id})"><td class="rank">${i+1}</td><td><strong>${esc(name(x.r))}</strong></td><td>${x.total}</td><td>${x.trades}</td><td>${x.waivers}</td><td>${x.adds}</td><td>${x.drops}</td><td>${x.faab?`$${x.faab}`:'—'}</td></tr>`).join('')}</tbody></table></div></div>`}
function activityView(){const rows=activityRows(),waivers=rows.filter(t=>t.type==='waiver').length,trades=rows.filter(t=>t.type==='trade').length,fa=rows.filter(t=>t.type==='free_agent').length;const tabs=[{id:'recent',label:'Recent Activity'},{id:'waivers',label:'Waiver / FAAB'},{id:'trades',label:'Trade Activity'},{id:'managers',label:'Manager Activity'}];const panel=activityTab==='waivers'?waiverPanel():activityTab==='trades'?tradeActivityPanel():activityTab==='managers'?managerPanel():recentPanel();return `<div class="grid grid-4 section-summary">${card('Transactions',rows.length,'Current season')}${card('Trades',trades,'Completed')}${card('Waivers',waivers,'Claims')}${card('Free Agents',fa,'Immediate adds')}</div>${innerNav(tabs,activityTab,'setActivityTab')}${panel}`}
const activityBaseRender=render;render=function(){if(S.view==='activity'){$('#pageTitle').textContent='League Activity';root.innerHTML=activityView();return}activityBaseRender()};window.render=render;
