const LEAGUE='1321261643883094016',API='https://api.sleeper.app/v1',RA='https://rosteraudit.com/wp-json/ra/v1';
let S={league:null,users:[],rosters:[],matchups:[],tx:[],drafts:[],picks:[],players:{},history:[],draftBoards:[],values:{},pickValues:[],movers:[],rankings:[],view:'home',team:null,format:'sf'};
const $=s=>document.querySelector(s),root=$('#viewRoot');
async function fetchJson(url){const r=await fetch(url);if(!r.ok)throw Error(`${r.status} ${url}`);return r.json()}
async function j(p){return fetchJson(API+p)}
async function safeUrl(url,fallback){try{return await fetchJson(url)}catch(e){console.warn('Optional data failed',url,e);return fallback}}
async function safe(p,fallback=[]){try{return await j(p)}catch{return fallback}}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function owner(id){return S.users.find(u=>u.user_id===id)}
function roster(id){return S.rosters.find(r=>Number(r.roster_id)===Number(id))}
function name(r){if(!r)return'Unknown Team';const u=owner(r.owner_id);return u?.metadata?.team_name||u?.display_name||`Team ${r.roster_id}`}
function rec(r){const s=r?.settings||{};return `${s.wins||0}-${s.losses||0}${s.ties?'-'+s.ties:''}`}
function pts(r){const s=r?.settings||{};return(Number(s.fpts||0)+Number(s.fpts_decimal||0)/100).toFixed(2)}
function player(id){if(S.players[id])return S.players[id];if(/^[A-Z]{2,3}$/.test(id||''))return{full_name:`${id} D/ST`,position:'DEF',team:id};return{full_name:`Player ${id}`,position:'—',team:'—'}}
function pname(id){const p=player(id);return p.full_name||[p.first_name,p.last_name].filter(Boolean).join(' ')||`Player ${id}`}
function posClass(pos=''){return `pos pos-${pos}`}
function fmt(n){return Number(n||0).toLocaleString()}
function dynastyValue(id){const v=S.values[id];return v?Number(S.format==='sf'?v.sf:v['1qb'])||0:0}
function currentFormat(){return S.format==='sf'?'Superflex':'1QB'}
function card(t,v,sub=''){return `<div class="card stat-card"><div class="muted">${esc(t)}</div><div class="metric">${esc(v)}</div><small class="muted">${esc(sub)}</small></div>`}
function date(ts){return ts?new Date(ts).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):'—'}
function standings(){return[...S.rosters].sort((a,b)=>(b.settings?.wins||0)-(a.settings?.wins||0)||Number(pts(b))-Number(pts(a)))}
async function loadHistory(){let id=S.league.previous_league_id,years=0,out=[];while(id&&id!=='0'&&years<6){const l=await safe('/league/'+id,null);if(!l)break;out.push(l);id=l.previous_league_id;years++}S.history=out}
async function loadTransactions(){const weeks=Array.from({length:18},(_,i)=>i+1);const all=await Promise.all(weeks.map(w=>safe(`/league/${LEAGUE}/transactions/${w}`,[])));const map=new Map;all.flat().forEach(t=>map.set(t.transaction_id,t));S.tx=[...map.values()].sort((a,b)=>(b.created||0)-(a.created||0))}
async function loadDraftBoards(){const leagues=[S.league,...S.history],drafts=[];for(const l of leagues){const ds=await safe(`/league/${l.league_id}/drafts`,[]);drafts.push(...ds)}const seen=new Map;drafts.forEach(d=>seen.set(d.draft_id,d));S.drafts=[...seen.values()].sort((a,b)=>(b.season||'').localeCompare(a.season||''));S.draftBoards=await Promise.all(S.drafts.map(async d=>({draft:d,picks:await safe(`/draft/${d.draft_id}/picks`,[])})))}
async function loadValues(){const formatKey=S.format==='sf'?'sf_ppr':'1qb_ppr';const [vals,picks,movers,ranks]=await Promise.all([safeUrl(`${RA}/rankings/values?format_key=${formatKey}`,{}),safeUrl(`${RA}/picks`,{picks:[]}),safeUrl(`${RA}/movers?limit=20`,{movers:[]}),safeUrl(`${RA}/rankings?format=${S.format}&per_page=100&league_size=${S.rosters.length||10}`,{players:[]})]);S.values=vals.values||vals||{};S.pickValues=picks.picks||[];S.movers=movers.movers||movers.players||[];S.rankings=ranks.players||ranks.rankings||[]}
async function load(){root.innerHTML='<div class="card">Loading live league + dynasty market data…</div>';try{S.league=await j('/league/'+LEAGUE);[S.users,S.rosters,S.picks,S.players]=await Promise.all([j(`/league/${LEAGUE}/users`),j(`/league/${LEAGUE}/rosters`),safe(`/league/${LEAGUE}/traded_picks`,[]),safe('/players/nfl',{})]);S.format=(S.league.roster_positions||[]).some(x=>x==='SUPER_FLEX')?'sf':'1qb';const wk=S.league.settings?.leg||1;S.matchups=await safe(`/league/${LEAGUE}/matchups/${wk}`,[]);await Promise.all([loadHistory(),loadTransactions()]);await Promise.all([loadDraftBoards(),loadValues()]);$('#leagueName').textContent=S.league.name||'LEAGUE HQ';$('#seasonLabel').textContent=`${S.league.season||'2026'} SEASON`;$('#weekLabel').textContent=`Week ${wk}`;$('#connectionText').textContent='Sleeper + values live';render()}catch(e){console.error(e);root.innerHTML='<div class="card notice"><h2>Could not load league data</h2><p class="muted">Refresh to retry the live connections.</p></div>'}}
function standingsTable(){return `<div class="card table-wrap"><table class="table"><thead><tr><th>#</th><th>Franchise</th><th>Record</th><th>PF</th><th>Dynasty Value</th></tr></thead><tbody>${standings().map((r,i)=>`<tr class="clickable" onclick="openTeam(${r.roster_id})"><td class="rank">${i+1}</td><td><strong>${esc(name(r))}</strong></td><td>${rec(r)}</td><td>${pts(r)}</td><td>${fmt(rosterValue(r))}</td></tr>`).join('')}</tbody></table></div>`}
function home(){const st=standings(),leader=st[0],power=powerRankings()[0],trades=S.tx.filter(t=>t.type==='trade');return `<div class="grid grid-4">${card('League Teams',S.rosters.length,'Sleeper franchises')}${card('Current Leader',leader?name(leader):'—',leader?rec(leader):'')}${card('Dynasty #1',power?name(power.r):'—',power?`${fmt(power.total)} franchise value`:'')}${card('Trades Logged',trades.length,'Current league season')}</div><div class="section-title"><h2>League Standings</h2><span class="badge">LIVE FROM SLEEPER</span></div>${standingsTable()}<div class="section-title"><h2>League HQ</h2></div><div class="grid grid-3"><button class="card feature link-card" onclick="go('values')"><h3>↗ Player Values</h3><p class="muted">Live ${currentFormat()} dynasty market values, rankings and movers.</p><strong>Open Values →</strong></button><button class="card feature link-card" onclick="go('power')"><h3>⚡ Power Rankings</h3><p class="muted">Roster strength plus future draft capital across every franchise.</p><strong>See rankings →</strong></button><button class="card feature link-card" onclick="go('draft')"><h3>★ Draft Grades</h3><p class="muted">See who won completed drafts based on what those players are worth today.</p><strong>Open Draft Center →</strong></button></div>${attribution()}`}
function teamLogo(r){const u=owner(r.owner_id);return u?.avatar?`<img class="team-logo" src="https://sleepercdn.com/avatars/thumbs/${u.avatar}" alt="">`:`<div class="avatar">${esc(name(r).slice(0,2).toUpperCase())}</div>`}
function rosterValue(r){return(r?.players||[]).reduce((a,id)=>a+dynastyValue(id),0)}
function starterValue(r){const s=new Set(r?.starters||[]);return(r?.players||[]).filter(id=>s.has(id)).reduce((a,id)=>a+dynastyValue(id),0)}
function teams(){return `<div class="grid grid-2">${powerRankings().map((x,i)=>`<button class="card team-card link-card" onclick="openTeam(${x.r.roster_id})">${teamLogo(x.r)}<div class="grow"><strong>#${i+1} ${esc(name(x.r))}</strong><div class="muted">${rec(x.r)} · ${fmt(x.players)} player value · ${fmt(x.picks)} picks</div></div><span class="arrow">→</span></button>`).join('')}</div>${attribution()}`}
function rosterRows(ids=[],r){const starters=new Set(r.starters||[]),reserve=new Set(r.reserve||[]),taxi=new Set(r.taxi||[]);return ids.map(id=>{const p=player(id);let role=starters.has(id)?'Starter':reserve.has(id)?'IR':taxi.has(id)?'Taxi':'Bench';return `<tr><td><span class="${posClass(p.position)}">${esc(p.position||'—')}</span></td><td><strong>${esc(pname(id))}</strong></td><td>${esc(p.team||'FA')}</td><td>${fmt(dynastyValue(id))}</td><td><span class="role role-${role.toLowerCase()}">${role}</span></td></tr>`}).join('')}
function currentPickOwner(season,round,original){const moved=S.picks.filter(p=>String(p.season)===String(season)&&Number(p.round)===round&&Number(p.roster_id)===Number(original));return moved.length?Number(moved[moved.length-1].owner_id):Number(original)}
function ownedPicks(rosterId){const start=Number(S.league.season||2026)+1,rounds=Math.max(3,Number(S.league.settings?.draft_rounds||4)),out=[];for(let y=start;y<start+3;y++)for(let rd=1;rd<=rounds;rd++)for(const original of S.rosters){if(currentPickOwner(y,rd,original.roster_id)===Number(rosterId))out.push({season:y,round:rd,original:original.roster_id})}return out}
function pickMarketValue(p){const match=S.pickValues.find(x=>Number(x.pick_season)===Number(p.season)&&Number(x.pick_round)===Number(p.round)&&x.pick_slot==='mid');if(match)return Number(S.format==='sf'?match.val_sf:match.val_1qb)||0;const fallback={1:1600,2:600,3:200,4:80};return fallback[p.round]||40}
function draftCapitalValue(id){return ownedPicks(id).reduce((a,p)=>a+pickMarketValue(p),0)}
function picksHtml(rosterId){const picks=ownedPicks(rosterId);if(!picks.length)return'<p class="muted">No future picks found.</p>';return `<div class="pick-grid">${picks.map(p=>`<div class="pick-chip"><strong>${p.season} R${p.round}</strong><small>${p.original===Number(rosterId)?'Own pick':`via ${esc(name(roster(p.original)))}`} · ${fmt(pickMarketValue(p))}</small></div>`).join('')}</div>`}
function teamDetail(id){const r=roster(id);if(!r)return teams();const ids=[...(r.players||[])].sort((a,b)=>dynastyValue(b)-dynastyValue(a));return `<button class="back-btn" onclick="go('teams')">← All Teams</button><div class="team-hero card">${teamLogo(r)}<div><div class="eyebrow">FRANCHISE</div><h2>${esc(name(r))}</h2><div class="muted">${rec(r)} · ${fmt(rosterValue(r))} roster value · ${fmt(draftCapitalValue(id))} draft capital</div></div></div><div class="grid grid-3 value-summary">${card('Roster Value',fmt(rosterValue(r)),currentFormat())}${card('Starter Value',fmt(starterValue(r)),'Current Sleeper starters')}${card('Draft Capital',fmt(draftCapitalValue(id)),'Mid-pick estimate')}</div><div class="grid team-detail-grid"><div><div class="section-title"><h2>Roster</h2><span class="badge">VALUE SORTED</span></div><div class="card table-wrap"><table class="table"><thead><tr><th>Pos</th><th>Player</th><th>NFL</th><th>Value</th><th>Status</th></tr></thead><tbody>${rosterRows(ids,r)}</tbody></table></div></div><div><div class="section-title"><h2>Draft Capital</h2></div><div class="card">${picksHtml(id)}</div></div></div>${attribution()}`}
function matchups(){const groups={};S.matchups.forEach(m=>(groups[m.matchup_id]??=[]).push(m));return `<div class="grid grid-2">${Object.values(groups).map(g=>`<div class="card matchup-card"><div class="eyebrow">MATCHUP ${g[0]?.matchup_id||''}</div>${g.map(m=>{const r=roster(m.roster_id);return `<button class="match-team" onclick="openTeam(${m.roster_id})"><strong>${esc(name(r))}</strong><span>${m.points??0}</span></button>`}).join('')}</div>`).join('')}</div>`}
function tradeAssetLines(t,rid){const adds=Object.entries(t.adds||{}).filter(([,to])=>Number(to)===Number(rid)).map(([id])=>`<span>${esc(pname(id))} <b>${fmt(dynastyValue(id))}</b></span>`);const picks=(t.draft_picks||[]).filter(p=>Number(p.owner_id)===Number(rid)).map(p=>`<span>${p.season} Round ${p.round}</span>`);return[...adds,...picks].join('')||'<span class="muted">No valued assets listed</span>'}
function trades(){const tx=S.tx.filter(t=>t.type==='trade'&&t.status==='complete');if(!tx.length)return placeholder('Trade Center','No completed trades were returned for the current league season yet.');return `<div class="section-title"><h2>Completed Trades</h2><span class="badge">CURRENT VALUES</span></div><div class="trade-list">${tx.map(t=>`<div class="card trade-card"><div class="trade-head"><strong>${date(t.created)}</strong><span class="badge">TRADE</span></div><div class="trade-sides">${(t.roster_ids||[]).map(rid=>`<div class="trade-side"><button onclick="openTeam(${rid})">${esc(name(roster(rid)))}</button><div class="asset-list">${tradeAssetLines(t,rid)}</div></div>`).join('')}</div></div>`).join('')}</div>${attribution()}`}
function values(){const ranks=(S.rankings.length?S.rankings:Object.keys(S.values).map(id=>({sleeper_id:id,name:pname(id),position:player(id).position,team:player(id).team,value:dynastyValue(id)}))).map(x=>({...x,_id:String(x.sleeper_id||x.player_id||x.id||''),_value:Number(x.value||x.val_sf||x.val_1qb||dynastyValue(String(x.sleeper_id||x.player_id||x.id||'')))||0})).sort((a,b)=>b._value-a._value).slice(0,100);return `<div class="grid grid-3">${card('Scoring Format',currentFormat(),`${S.rosters.length}-team league`)}${card('Players Valued',Object.keys(S.values).length,'Live market lookup')}${card('Value Source','RosterAudit','Trade-derived dynasty market')}</div><div class="section-title"><h2>Dynasty Rankings</h2><span class="badge">TOP 100</span></div><div class="card search-card"><input id="valueSearch" class="search-input" placeholder="Search player, position or NFL team…" oninput="filterValues()"></div><div class="card table-wrap"><table class="table value-table"><thead><tr><th>#</th><th>Player</th><th>Pos</th><th>NFL</th><th>Value</th></tr></thead><tbody id="valueRows">${ranks.map((x,i)=>`<tr data-search="${esc(`${x.name||pname(x._id)} ${x.position||player(x._id).position} ${x.team||player(x._id).team}`.toLowerCase())}"><td class="rank">${i+1}</td><td><strong>${esc(x.name||pname(x._id))}</strong></td><td>${esc(x.position||player(x._id).position||'—')}</td><td>${esc(x.team||player(x._id).team||'FA')}</td><td><strong>${fmt(x._value)}</strong></td></tr>`).join('')}</tbody></table></div>${moversHtml()}${attribution()}`}
function moversHtml(){if(!S.movers.length)return'';return `<div class="section-title"><h2>Market Movers</h2><span class="badge">LIVE</span></div><div class="grid grid-2">${S.movers.slice(0,10).map(m=>`<div class="card mover"><div><strong>${esc(m.name||pname(String(m.sleeper_id||m.player_id||'')))}</strong><div class="muted">${esc(m.position||'')} ${esc(m.team||'')}</div></div><div class="metric-small ${Number(m.trend_7d||m.change||0)>=0?'up':'down'}">${Number(m.trend_7d||m.change||0)>=0?'+':''}${fmt(m.trend_7d||m.change||0)}</div></div>`).join('')}</div>`}
function filterValues(){const q=($('#valueSearch')?.value||'').toLowerCase();document.querySelectorAll('#valueRows tr').forEach(r=>r.style.display=(r.dataset.search||'').includes(q)?'':'none')}
function powerRankings(){const rows=S.rosters.map(r=>({r,players:rosterValue(r),starters:starterValue(r),picks:draftCapitalValue(r.roster_id)}));const maxP=Math.max(...rows.map(x=>x.players),1),maxS=Math.max(...rows.map(x=>x.starters),1),maxD=Math.max(...rows.map(x=>x.picks),1);rows.forEach(x=>{x.score=(x.players/maxP)*50+(x.starters/maxS)*30+(x.picks/maxD)*20;x.total=x.players+x.picks});return rows.sort((a,b)=>b.score-a.score)}
function power(){const rows=powerRankings();return `<div class="grid grid-3">${card('Model','50 / 30 / 20','Roster / starters / picks')}${card('Format',currentFormat(),'Automatically detected')}${card('Value Source','RosterAudit','Live dynasty market')}</div><div class="section-title"><h2>Franchise Power Rankings</h2><span class="badge">DYNASTY + CONTENDER</span></div><div class="card table-wrap"><table class="table"><thead><tr><th>#</th><th>Franchise</th><th>Score</th><th>Roster</th><th>Starters</th><th>Picks</th><th>Total Assets</th></tr></thead><tbody>${rows.map((x,i)=>`<tr class="clickable" onclick="openTeam(${x.r.roster_id})"><td class="rank">${i+1}</td><td><strong>${esc(name(x.r))}</strong></td><td><span class="score-pill">${x.score.toFixed(1)}</span></td><td>${fmt(x.players)}</td><td>${fmt(x.starters)}</td><td>${fmt(x.picks)}</td><td><strong>${fmt(x.total)}</strong></td></tr>`).join('')}</tbody></table></div><div class="card methodology"><h3>How this works</h3><p class="muted">The score blends total roster dynasty value (50%), current Sleeper starter value (30%), and future draft capital (20%). It is intended as a league-specific power index, not a projection of exact win probability.</p></div>${attribution()}`}
function draftGrades(board){const ps=(board.picks||[]).filter(p=>p.player_id);if(!ps.length)return[];const current=ps.map(p=>({...p,value:dynastyValue(String(p.player_id))}));const sortedVals=current.map(x=>x.value).sort((a,b)=>b-a);const teams={};current.forEach(p=>{const rid=Number(p.roster_id);if(!teams[rid])teams[rid]={rid,total:0,roi:0,picks:[],best:null};const expected=sortedVals[Math.max(0,Math.min(sortedVals.length-1,Number(p.pick_no)-1))]||0,delta=p.value-expected;teams[rid].total+=p.value;teams[rid].roi+=delta;teams[rid].picks.push({...p,delta});if(!teams[rid].best||delta>teams[rid].best.delta)teams[rid].best={...p,delta}});const arr=Object.values(teams).sort((a,b)=>(b.total+b.roi*.35)-(a.total+a.roi*.35));const max=Math.max(...arr.map(x=>x.total+x.roi*.35),1),min=Math.min(...arr.map(x=>x.total+x.roi*.35));arr.forEach((x,i)=>{const score=x.total+x.roi*.35,pct=max===min?1:(score-min)/(max-min);x.grade=pct>.88?'A+':pct>.72?'A':pct>.55?'B+':pct>.38?'B':pct>.22?'C+':'C';x.rank=i+1});return arr}
function gradeSection(board){if(board.draft.status!=='complete')return'';const grades=draftGrades(board);if(!grades.length)return'';const champ=grades[0];return `<div class="card grade-card"><div class="winner-banner"><div><div class="eyebrow">WHO WON THE ${esc(board.draft.season)} DRAFT?</div><h3>🏆 ${esc(name(roster(champ.rid)))}</h3><p class="muted">${fmt(champ.total)} current player value · ${champ.roi>=0?'+':''}${fmt(champ.roi)} vs hindsight slot curve</p></div><div class="grade-big">${champ.grade}</div></div><div class="grade-grid">${grades.map(g=>`<div class="grade-row"><span class="rank">${g.rank}</span><div class="grow"><strong>${esc(name(roster(g.rid)))}</strong><small>${g.best?`Best value: ${esc(pname(String(g.best.player_id)))} (${g.best.delta>=0?'+':''}${fmt(g.best.delta)})`:''}</small></div><span>${fmt(g.total)}</span><b>${g.grade}</b></div>`).join('')}</div><p class="fineprint">Retrospective grade: current dynasty value compared with a hindsight redraft value curve. This does not claim the pick was good or bad based on information available on draft day.</p></div>`}
function draftBoard(board){const d=board.draft,ps=board.picks||[];if(!ps.length)return `<div class="card"><h3>${esc(d.season)} Draft</h3><p class="muted">No completed picks returned yet.</p></div>`;return `${gradeSection(board)}<div class="card draft-board"><div class="trade-head"><div><div class="eyebrow">${esc(d.type||'ROOKIE')} DRAFT</div><h3>${esc(d.metadata?.name||`${d.season} Draft`)}</h3></div><span class="badge">${ps.length} PICKS</span></div><div class="draft-picks">${ps.map(p=>`<div class="draft-pick"><span class="pick-no">${p.round}.${String(((p.pick_no-1)%Number(d.settings?.teams||S.rosters.length))+1).padStart(2,'0')}</span><div class="grow"><strong>${esc(p.metadata?.first_name||player(p.player_id).first_name||'')} ${esc(p.metadata?.last_name||player(p.player_id).last_name||'')}</strong><small>${esc(p.metadata?.position||player(p.player_id).position||'—')} · ${esc(name(roster(p.roster_id)))}</small></div><b>${fmt(dynastyValue(String(p.player_id)))}</b></div>`).join('')}</div></div>`}
function draft(){const complete=S.draftBoards.filter(x=>x.draft.status==='complete'&&(x.picks||[]).length),latest=complete[0],winner=latest?draftGrades(latest)[0]:null;return `<div class="grid grid-4">${card('Drafts Found',S.draftBoards.length,'Current + historical')}${card('Latest Draft Winner',winner?name(roster(winner.rid)):'—',latest?`${latest.draft.season} retrospective`:'No completed draft')}${card('Future Pick Value',fmt(S.rosters.reduce((a,r)=>a+draftCapitalValue(r.roster_id),0)),'League-wide capital')}${card('Value Format',currentFormat(),'RosterAudit market')}</div><div class="section-title"><h2>Future Draft Capital</h2><span class="badge">CURRENT OWNERSHIP</span></div><div class="grid grid-2">${powerRankings().map(x=>`<div class="card"><button class="team-title" onclick="openTeam(${x.r.roster_id})">${esc(name(x.r))} · ${fmt(x.picks)}</button>${picksHtml(x.r.roster_id)}</div>`).join('')}</div><div class="section-title"><h2>Draft History & Grades</h2><span class="badge">CURRENT VALUE RETROSPECTIVE</span></div><div class="draft-history">${S.draftBoards.map(draftBoard).join('')||'<div class="card muted">No draft boards found.</div>'}</div>${attribution()}`}
function attribution(){return `<div class="attribution">Dynasty values powered by <a href="https://rosteraudit.com" target="_blank" rel="noopener">RosterAudit.com</a>. Sleeper supplies league, roster, transaction and draft data.</div>`}
function placeholder(title,body){return `<div class="card notice"><h2>${esc(title)}</h2><p class="muted">${esc(body)}</p></div>`}
function render(){const titles={home:'League Headquarters',teams:S.team?'Franchise':'Franchises',matchups:'Matchups',standings:'Standings',trades:'Trade Center',values:'Player Values',draft:'Draft Center',power:'Power Rankings',sportsbook:'Sportsbook',finances:'League Finances',history:'League History',reports:'Tuesday League Report'};$('#pageTitle').textContent=titles[S.view];if(S.view==='home')root.innerHTML=home();else if(S.view==='teams')root.innerHTML=S.team?teamDetail(S.team):teams();else if(S.view==='matchups')root.innerHTML=matchups();else if(S.view==='standings')root.innerHTML=standingsTable();else if(S.view==='trades')root.innerHTML=trades();else if(S.view==='values')root.innerHTML=values();else if(S.view==='draft')root.innerHTML=draft();else if(S.view==='power')root.innerHTML=power();else{const copy={sportsbook:'Informational NFL odds and player props are planned next. Wagers will only be placed at licensed sportsbooks.',finances:'LeagueSafe dues status, prize pool and payout structure will be tracked here; this site will not custody league funds.',history:'Champions, records, historical finishes and rivalry records will build from archived Sleeper seasons.',reports:'Owners will be able to opt into an automatically generated Tuesday league newsletter.'};root.innerHTML=placeholder(titles[S.view],copy[S.view])}}
function go(v){S.view=v;S.team=null;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));render();window.scrollTo({top:0,behavior:'smooth'});$('#sidebar').classList.remove('open')}
function openTeam(id){S.view='teams';S.team=Number(id);document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view==='teams'));render();window.scrollTo({top:0,behavior:'smooth'})}
window.go=go;window.openTeam=openTeam;window.filterValues=filterValues;
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>go(b.dataset.view));$('#refreshBtn').onclick=load;$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');load();