const LEAGUE='1321261643883094016',API='https://api.sleeper.app/v1';
let S={league:null,users:[],rosters:[],matchups:[],tx:[],drafts:[],picks:[],players:{},history:[],draftBoards:[],view:'home',team:null};
const $=s=>document.querySelector(s),root=$('#viewRoot');
async function j(p){const r=await fetch(API+p);if(!r.ok)throw Error(`${r.status} ${p}`);return r.json()}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function owner(id){return S.users.find(u=>u.user_id===id)}
function roster(id){return S.rosters.find(r=>Number(r.roster_id)===Number(id))}
function name(r){if(!r)return'Unknown Team';const u=owner(r.owner_id);return u?.metadata?.team_name||u?.display_name||`Team ${r.roster_id}`}
function rec(r){const s=r?.settings||{};return `${s.wins||0}-${s.losses||0}${s.ties?'-'+s.ties:''}`}
function pts(r){const s=r?.settings||{};return(Number(s.fpts||0)+Number(s.fpts_decimal||0)/100).toFixed(2)}
function player(id){if(S.players[id])return S.players[id];if(/^[A-Z]{2,3}$/.test(id||''))return{full_name:`${id} D/ST`,position:'DEF',team:id};return{full_name:`Player ${id}`,position:'—',team:'—'}}
function pname(id){const p=player(id);return p.full_name||[p.first_name,p.last_name].filter(Boolean).join(' ')||`Player ${id}`}
function posClass(pos=''){return `pos pos-${pos}`}
function card(t,v,sub=''){return `<div class="card stat-card"><div class="muted">${esc(t)}</div><div class="metric">${esc(v)}</div><small class="muted">${esc(sub)}</small></div>`}
function date(ts){return ts?new Date(ts).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):'—'}
function standings(){return[...S.rosters].sort((a,b)=>(b.settings?.wins||0)-(a.settings?.wins||0)||Number(pts(b))-Number(pts(a)))}
async function safe(p,fallback=[]){try{return await j(p)}catch{return fallback}}
async function loadHistory(){let id=S.league.previous_league_id,years=0,out=[];while(id&&id!=='0'&&years<6){const l=await safe('/league/'+id,null);if(!l)break;out.push(l);id=l.previous_league_id;years++}S.history=out}
async function loadTransactions(){const weeks=Array.from({length:18},(_,i)=>i+1);const all=await Promise.all(weeks.map(w=>safe(`/league/${LEAGUE}/transactions/${w}`,[])));const map=new Map;all.flat().forEach(t=>map.set(t.transaction_id,t));S.tx=[...map.values()].sort((a,b)=>(b.created||0)-(a.created||0))}
async function loadDraftBoards(){const leagues=[S.league,...S.history],drafts=[];for(const l of leagues){const ds=await safe(`/league/${l.league_id}/drafts`,[]);drafts.push(...ds)}const seen=new Map;drafts.forEach(d=>seen.set(d.draft_id,d));S.drafts=[...seen.values()].sort((a,b)=>(b.season||'').localeCompare(a.season||''));S.draftBoards=await Promise.all(S.drafts.map(async d=>({draft:d,picks:await safe(`/draft/${d.draft_id}/picks`,[])})))}
async function load(){root.innerHTML='<div class="card">Loading live league data…</div>';try{S.league=await j('/league/'+LEAGUE);[S.users,S.rosters,S.picks,S.players]=await Promise.all([j(`/league/${LEAGUE}/users`),j(`/league/${LEAGUE}/rosters`),safe(`/league/${LEAGUE}/traded_picks`,[]),safe('/players/nfl',{})]);const wk=S.league.settings?.leg||1;S.matchups=await safe(`/league/${LEAGUE}/matchups/${wk}`,[]);await Promise.all([loadHistory(),loadTransactions()]);await loadDraftBoards();$('#leagueName').textContent=S.league.name||'LEAGUE HQ';$('#seasonLabel').textContent=`${S.league.season||'2026'} SEASON`;$('#weekLabel').textContent=`Week ${wk}`;$('#connectionText').textContent='Sleeper connected';render()}catch(e){console.error(e);root.innerHTML='<div class="card notice"><h2>Could not reach Sleeper</h2><p class="muted">Refresh to retry the live league connection.</p></div>'}}
function standingsTable(){return `<div class="card table-wrap"><table class="table"><thead><tr><th>#</th><th>Franchise</th><th>Record</th><th>PF</th><th>Moves</th></tr></thead><tbody>${standings().map((r,i)=>`<tr class="clickable" onclick="openTeam(${r.roster_id})"><td class="rank">${i+1}</td><td><strong>${esc(name(r))}</strong></td><td>${rec(r)}</td><td>${pts(r)}</td><td>${r.settings?.total_moves||0}</td></tr>`).join('')}</tbody></table></div>`}
function home(){const st=standings(),leader=st[0],trades=S.tx.filter(t=>t.type==='trade');return `<div class="grid grid-4">${card('League Teams',S.rosters.length,'Sleeper franchises')}${card('Current Leader',leader?name(leader):'—',leader?rec(leader):'')}${card('Trades Logged',trades.length,'Current league season')}${card('Drafts Found',S.draftBoards.length,'Current + prior league IDs')}</div><div class="section-title"><h2>League Standings</h2><span class="badge">LIVE FROM SLEEPER</span></div>${standingsTable()}<div class="section-title"><h2>League HQ</h2></div><div class="grid grid-3"><button class="card feature link-card" onclick="go('draft')"><h3>★ Draft Center</h3><p class="muted">Real draft boards, future capital and historical rookie picks.</p><strong>Open Draft Center →</strong></button><button class="card feature link-card" onclick="go('trades')"><h3>⇄ Trade Center</h3><p class="muted">Completed trades with players and draft picks changing hands.</p><strong>Open Trade Center →</strong></button><button class="card feature link-card" onclick="go('teams')"><h3>◉ Franchises</h3><p class="muted">Starters, bench, taxi, IR and future draft capital by owner.</p><strong>View teams →</strong></button></div>`}
function teamLogo(r){const u=owner(r.owner_id);return u?.avatar?`<img class="team-logo" src="https://sleepercdn.com/avatars/thumbs/${u.avatar}" alt="">`:`<div class="avatar">${esc(name(r).slice(0,2).toUpperCase())}</div>`}
function teams(){return `<div class="grid grid-2">${standings().map(r=>`<button class="card team-card link-card" onclick="openTeam(${r.roster_id})">${teamLogo(r)}<div class="grow"><strong>${esc(name(r))}</strong><div class="muted">${rec(r)} · ${r.players?.length||0} players</div></div><span class="arrow">→</span></button>`).join('')}</div>`}
function rosterRows(ids=[],r){const starters=new Set(r.starters||[]),reserve=new Set(r.reserve||[]),taxi=new Set(r.taxi||[]);return ids.map(id=>{const p=player(id);let role=starters.has(id)?'Starter':reserve.has(id)?'IR':taxi.has(id)?'Taxi':'Bench';return `<tr><td><span class="${posClass(p.position)}">${esc(p.position||'—')}</span></td><td><strong>${esc(pname(id))}</strong></td><td>${esc(p.team||'FA')}</td><td><span class="role role-${role.toLowerCase()}">${role}</span></td></tr>`}).join('')}
function currentPickOwner(season,round,original){const moved=S.picks.filter(p=>String(p.season)===String(season)&&Number(p.round)===round&&Number(p.roster_id)===Number(original));return moved.length?Number(moved[moved.length-1].owner_id):Number(original)}
function ownedPicks(rosterId){const start=Number(S.league.season||2026)+1,rounds=Math.max(3,Number(S.league.settings?.draft_rounds||4)),out=[];for(let y=start;y<start+3;y++)for(let rd=1;rd<=rounds;rd++)for(const original of S.rosters){if(currentPickOwner(y,rd,original.roster_id)===Number(rosterId))out.push({season:y,round:rd,original:original.roster_id})}return out}
function picksHtml(rosterId){const picks=ownedPicks(rosterId);if(!picks.length)return'<p class="muted">No future picks found.</p>';return `<div class="pick-grid">${picks.map(p=>`<div class="pick-chip"><strong>${p.season} R${p.round}</strong><small>${p.original===Number(rosterId)?'Own pick':`via ${esc(name(roster(p.original)))}`}</small></div>`).join('')}</div>`}
function teamDetail(id){const r=roster(id);if(!r)return teams();const ids=[...(r.players||[])].sort((a,b)=>{const order={QB:1,RB:2,WR:3,TE:4,K:5,DEF:6};return(order[player(a).position]||9)-(order[player(b).position]||9)||pname(a).localeCompare(pname(b))});return `<button class="back-btn" onclick="go('teams')">← All Teams</button><div class="team-hero card">${teamLogo(r)}<div><div class="eyebrow">FRANCHISE</div><h2>${esc(name(r))}</h2><div class="muted">${rec(r)} · ${pts(r)} PF · ${r.settings?.total_moves||0} moves</div></div></div><div class="grid team-detail-grid"><div><div class="section-title"><h2>Roster</h2><span class="badge">${ids.length} PLAYERS</span></div><div class="card table-wrap"><table class="table"><thead><tr><th>Pos</th><th>Player</th><th>NFL</th><th>Status</th></tr></thead><tbody>${rosterRows(ids,r)}</tbody></table></div></div><div><div class="section-title"><h2>Draft Capital</h2></div><div class="card">${picksHtml(id)}</div></div></div>`}
function matchups(){const groups={};S.matchups.forEach(m=>(groups[m.matchup_id]??=[]).push(m));return `<div class="grid grid-2">${Object.values(groups).map(g=>`<div class="card matchup-card"><div class="eyebrow">MATCHUP ${g[0]?.matchup_id||''}</div>${g.map(m=>{const r=roster(m.roster_id);return `<button class="match-team" onclick="openTeam(${m.roster_id})"><strong>${esc(name(r))}</strong><span>${m.points??0}</span></button>`}).join('')}</div>`).join('')}</div>`}
function tradeAssetLines(t,rid){const adds=Object.entries(t.adds||{}).filter(([,to])=>Number(to)===Number(rid)).map(([id])=>`<span>${esc(pname(id))}</span>`);const picks=(t.draft_picks||[]).filter(p=>Number(p.owner_id)===Number(rid)).map(p=>`<span>${p.season} Round ${p.round} <small class="muted">(${esc(name(roster(p.roster_id)))})</small></span>`);const faab=(t.waiver_budget||[]).filter(x=>Number(x.receiver)===Number(rid)).map(x=>`<span>$${x.amount} FAAB</span>`);const lines=[...adds,...picks,...faab];return lines.length?lines.join(''):'<span class="muted">No player/pick assets listed</span>'}
function trades(){const tx=S.tx.filter(t=>t.type==='trade'&&t.status==='complete');if(!tx.length)return placeholder('Trade Center','No completed trades were returned for the current league season yet.');return `<div class="section-title"><h2>Completed Trades</h2><span class="badge">${tx.length} FOUND</span></div><div class="trade-list">${tx.map(t=>`<div class="card trade-card"><div class="trade-head"><strong>${date(t.created)}</strong><span class="badge">TRADE</span></div><div class="trade-sides">${(t.roster_ids||[]).map(rid=>`<div class="trade-side"><button onclick="openTeam(${rid})">${esc(name(roster(rid)))}</button><div class="asset-list">${tradeAssetLines(t,rid)}</div></div>`).join('')}</div></div>`).join('')}</div>`}
function draftBoard(board){const d=board.draft,ps=board.picks||[];if(!ps.length)return `<div class="card"><h3>${esc(d.season)} Draft</h3><p class="muted">No completed picks returned yet.</p></div>`;return `<div class="card draft-board"><div class="trade-head"><div><div class="eyebrow">${esc(d.type||'ROOKIE')} DRAFT</div><h3>${esc(d.metadata?.name||`${d.season} Draft`)}</h3></div><span class="badge">${ps.length} PICKS</span></div><div class="draft-picks">${ps.map(p=>`<div class="draft-pick"><span class="pick-no">${p.round}.${String(((p.pick_no-1)%Number(d.settings?.teams||S.rosters.length))+1).padStart(2,'0')}</span><div><strong>${esc(p.metadata?.first_name||player(p.player_id).first_name||'')} ${esc(p.metadata?.last_name||player(p.player_id).last_name||'')}</strong><small>${esc(p.metadata?.position||player(p.player_id).position||'—')} · ${esc(name(roster(p.roster_id)))}</small></div></div>`).join('')}</div></div>`}
function draft(){const start=Number(S.league.season||2026)+1;return `<div class="grid grid-4">${card('Drafts Found',S.draftBoards.length,'Current + historical')}${card('Future Picks Traded',S.picks.length,'Sleeper ledger')}${card('Next Class',start,'Prospect hub next')}${card('Draft Grading','Next layer','Value-at-pick model')}</div><div class="section-title"><h2>Future Draft Capital</h2><span class="badge">CURRENT OWNERSHIP</span></div><div class="grid grid-2">${S.rosters.map(r=>`<div class="card"><button class="team-title" onclick="openTeam(${r.roster_id})">${esc(name(r))}</button>${picksHtml(r.roster_id)}</div>`).join('')}</div><div class="section-title"><h2>Draft History</h2><span class="badge">SLEEPER BOARDS</span></div><div class="draft-history">${S.draftBoards.map(draftBoard).join('')||'<div class="card muted">No draft boards found.</div>'}</div><div class="card notice coming"><h3>Next: Who Won the Draft?</h3><p class="muted">The next layer will score each class using draft position versus current authorized dynasty value, while keeping a separate draft-day grade so hindsight does not rewrite what was reasonable at the time.</p></div>`}
function placeholder(title,body){return `<div class="card notice"><h2>${esc(title)}</h2><p class="muted">${esc(body)}</p></div>`}
function render(){const titles={home:'League Headquarters',teams:S.team?'Franchise':'Franchises',matchups:'Matchups',standings:'Standings',trades:'Trade Center',values:'Player Values',draft:'Draft Center',power:'Power Rankings',sportsbook:'Sportsbook',finances:'League Finances',history:'League History',reports:'Tuesday League Report'};$('#pageTitle').textContent=titles[S.view];if(S.view==='home')root.innerHTML=home();else if(S.view==='teams')root.innerHTML=S.team?teamDetail(S.team):teams();else if(S.view==='matchups')root.innerHTML=matchups();else if(S.view==='standings')root.innerHTML=standingsTable();else if(S.view==='trades')root.innerHTML=trades();else if(S.view==='draft')root.innerHTML=draft();else{const copy={values:'Authorized dynasty market values, player search, roster values and KeepTradeCut link-outs are the next integration.',power:'Contender strength, dynasty value and draft capital will combine into franchise rankings after the value feed is connected.',sportsbook:'Informational NFL odds and player props will be shown here. Wagers will only be placed at licensed sportsbooks.',finances:'LeagueSafe dues status, prize pool and payout structure will be tracked here; this site will not custody league funds.',history:'Champions, records, historical finishes and rivalry records will build from archived Sleeper seasons.',reports:'Owners will be able to opt into an automatically generated Tuesday league newsletter.'};root.innerHTML=placeholder(titles[S.view],copy[S.view])}}
function go(v){S.view=v;S.team=null;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));render();window.scrollTo({top:0,behavior:'smooth'});$('#sidebar').classList.remove('open')}
function openTeam(id){S.view='teams';S.team=Number(id);document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view==='teams'));render();window.scrollTo({top:0,behavior:'smooth'})}
window.go=go;window.openTeam=openTeam;
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>go(b.dataset.view));$('#refreshBtn').onclick=load;$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');load();