let financesTab='ledger';
function setFinancesTab(id){financesTab=id;render();window.scrollTo({top:0,behavior:'smooth'})}
window.setFinancesTab=setFinancesTab;
function financeState(){try{return JSON.parse(localStorage.getItem('leagueHQFinances')||'{}')}catch{return{}}}
function saveFinanceState(s){localStorage.setItem('leagueHQFinances',JSON.stringify(s))}
function defaultFinanceState(){const old=financeState();return{buyIn:Number(old.buyIn||0),leagueSafe:old.leagueSafe||'',paid:old.paid||{},payouts:old.payouts||[{label:'Champion',amount:0},{label:'Runner-up',amount:0},{label:'3rd Place',amount:0},{label:'Regular Season Winner',amount:0}],notes:old.notes||''}}
function money(n){return '$'+Number(n||0).toLocaleString(undefined,{minimumFractionDigits:0,maximumFractionDigits:2})}
function financeSummary(){const s=defaultFinanceState(),teams=S.rosters.length,paidCount=S.rosters.filter(r=>s.paid[String(r.roster_id)]).length,pool=s.buyIn*teams,payoutTotal=s.payouts.reduce((a,x)=>a+Number(x.amount||0),0);return{s,teams,paidCount,pool,payoutTotal,remaining:pool-payoutTotal}}
function financeLedger(){const {s,teams,paidCount,pool}=financeSummary();return `<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">DUES TRACKER</div><h2>League Payment Ledger</h2></div><p class="muted">Track who has paid league dues. League HQ records status only; it does not hold funds.</p></div><div class="grid grid-3 section-summary">${card('Buy-In',s.buyIn?money(s.buyIn):'Not Set','Per franchise')}${card('Collected',money(s.buyIn*paidCount),`${paidCount} of ${teams} paid`)}${card('Prize Pool',money(pool),'If every team pays')}</div><div class="card table-wrap"><table class="table finance-table"><thead><tr><th>Franchise</th><th>Buy-In</th><th>Status</th><th>Action</th></tr></thead><tbody>${standings().map(r=>{const paid=!!s.paid[String(r.roster_id)];return `<tr><td><strong>${esc(name(r))}</strong></td><td>${s.buyIn?money(s.buyIn):'—'}</td><td><span class="finance-status ${paid?'paid':'unpaid'}">${paid?'PAID':'UNPAID'}</span></td><td><button class="finance-toggle" onclick="togglePaid(${r.roster_id})">Mark ${paid?'Unpaid':'Paid'}</button></td></tr>`}).join('')}</tbody></table></div>${s.leagueSafe?`<div class="card finance-link-card"><div><div class="eyebrow">PAYMENT SERVICE</div><h3>LeagueSafe</h3><p class="muted">League dues and payouts are handled outside League HQ.</p></div><a class="finance-link" href="${esc(s.leagueSafe)}" target="_blank" rel="noopener noreferrer">Open LeagueSafe ↗</a></div>`:''}</div>`}
function togglePaid(id){const s=defaultFinanceState(),k=String(id);s.paid[k]=!s.paid[k];saveFinanceState(s);render()}
window.togglePaid=togglePaid;
function payoutsPanel(){const {s,pool,payoutTotal,remaining}=financeSummary();return `<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">PRIZE STRUCTURE</div><h2>Season Payouts</h2></div><p class="muted">Set the prize structure and immediately see whether the planned payouts match the available pool.</p></div><div class="grid grid-3 section-summary">${card('Available Pool',money(pool),'Based on current buy-in')}${card('Planned Payouts',money(payoutTotal),'Across all prize categories')}${card('Unallocated',money(remaining),remaining===0?'Pool fully allocated':remaining>0?'Still available':'Over-allocated')}</div><div class="card payout-editor"><div class="payout-rows">${s.payouts.map((p,i)=>`<div class="payout-row"><input class="finance-input" id="payoutLabel${i}" value="${esc(p.label)}" aria-label="Payout label"><div class="money-input"><span>$</span><input class="finance-input" id="payoutAmount${i}" type="number" min="0" step="1" value="${Number(p.amount||0)}" aria-label="Payout amount"></div></div>`).join('')}</div><div class="finance-actions"><button class="finance-primary" onclick="savePayouts()">Save Payout Structure</button></div></div><div class="card payout-preview"><div class="eyebrow">PAYOUT PREVIEW</div>${s.payouts.filter(x=>Number(x.amount)>0).map(x=>`<div class="payout-preview-row"><strong>${esc(x.label)}</strong><span>${money(x.amount)}</span></div>`).join('')||'<p class="muted">No payout amounts have been entered yet.</p>'}</div></div>`}
function savePayouts(){const s=defaultFinanceState();s.payouts=s.payouts.map((p,i)=>({label:document.querySelector(`#payoutLabel${i}`)?.value.trim()||p.label,amount:Number(document.querySelector(`#payoutAmount${i}`)?.value||0)}));saveFinanceState(s);render()}
window.savePayouts=savePayouts;
function settlementPanel(){const {s,pool,payoutTotal}=financeSummary();const active=s.payouts.filter(x=>Number(x.amount)>0);return `<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">SEASON-END TOOL</div><h2>Payout Calculator</h2></div><p class="muted">Assign each prize to the winning franchise and get a clean payout instruction sheet.</p></div><div class="card settlement-grid">${active.map((p,i)=>`<label><span>${esc(p.label)} · ${money(p.amount)}</span><select class="finance-select" id="winner${i}"><option value="">Select franchise</option>${S.rosters.map(r=>`<option value="${r.roster_id}">${esc(name(r))}</option>`).join('')}</select></label>`).join('')||'<p class="muted">Enter your payout structure first.</p>'}<div class="finance-actions"><button class="finance-primary" onclick="calculateSettlement()">Calculate Final Payouts</button></div></div><div id="settlementResult"></div><div class="card notice"><h3>Funds stay outside League HQ</h3><p class="muted">This calculator creates payout instructions only. Actual money should be distributed through LeagueSafe or another trusted payment method.</p></div></div>`}
function calculateSettlement(){const s=defaultFinanceState(),active=s.payouts.filter(x=>Number(x.amount)>0),totals={};active.forEach((p,i)=>{const rid=document.querySelector(`#winner${i}`)?.value;if(rid){totals[rid]=(totals[rid]||0)+Number(p.amount)}});const box=document.querySelector('#settlementResult');if(!box)return;const rows=Object.entries(totals).sort((a,b)=>b[1]-a[1]);box.innerHTML=`<div class="card payout-preview"><div class="eyebrow">FINAL PAYOUT INSTRUCTIONS</div>${rows.map(([rid,amt])=>`<div class="payout-preview-row"><strong>${esc(name(roster(rid)))}</strong><span>${money(amt)}</span></div>`).join('')||'<p class="muted">Select at least one prize winner.</p>'}</div>`}
window.calculateSettlement=calculateSettlement;
function financeSettings(){const s=defaultFinanceState();return `<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">COMMISSIONER SETTINGS</div><h2>Financial Setup</h2></div><p class="muted">Set the league buy-in and optional external LeagueSafe link.</p></div><div class="card finance-settings"><label>Buy-in per franchise<div class="money-input"><span>$</span><input id="financeBuyIn" class="finance-input" type="number" min="0" step="1" value="${s.buyIn||''}" placeholder="100"></div></label><label>LeagueSafe league URL<input id="financeLeagueSafe" class="finance-input" type="url" value="${esc(s.leagueSafe)}" placeholder="https://www.leaguesafe.com/..."></label><label>Commissioner note<textarea id="financeNotes" class="finance-input finance-textarea" placeholder="Payment deadline, payout rules, etc.">${esc(s.notes)}</textarea></label><button class="finance-primary" onclick="saveFinanceSettings()">Save Financial Settings</button></div><div class="card notice"><h3>Storage note</h3><p class="muted">For now, commissioner finance settings and paid/unpaid checkmarks are stored in this browser. The next infrastructure upgrade can move this ledger to shared persistent storage so every league member sees the same payment status.</p></div></div>`}
function saveFinanceSettings(){const s=defaultFinanceState();s.buyIn=Number(document.querySelector('#financeBuyIn')?.value||0);s.leagueSafe=document.querySelector('#financeLeagueSafe')?.value.trim()||'';s.notes=document.querySelector('#financeNotes')?.value.trim()||'';saveFinanceState(s);render()}
window.saveFinanceSettings=saveFinanceSettings;
function financesView(){const x=financeSummary(),tabs=[{id:'ledger',label:'Dues Ledger'},{id:'payouts',label:'Payout Structure'},{id:'settlement',label:'Season-End Payouts'},{id:'settings',label:'Commissioner Settings'}],panel=financesTab==='payouts'?payoutsPanel():financesTab==='settlement'?settlementPanel():financesTab==='settings'?financeSettings():financeLedger();return `<div class="grid grid-4 section-summary">${card('Teams',x.teams,'Sleeper franchises')}${card('Paid',`${x.paidCount}/${x.teams}`,'Dues status')}${card('Projected Pool',money(x.pool),'At full collection')}${card('Custody','External','League HQ holds $0')}</div>${innerNav(tabs,financesTab,'setFinancesTab')}${panel}`}
const financesBaseRender=render;
render=function(){if(S.view==='finances'){$('#pageTitle').textContent='League Finances';root.innerHTML=financesView();return}financesBaseRender()};
window.render=render;
