let outlookTab='matrix';
function setOutlookTab(id){outlookTab=id;render();window.scrollTo({top:0,behavior:'smooth'})}
window.setOutlookTab=setOutlookTab;
function fantasyAges(r){return (r.players||[]).map(id=>{const p=player(id);return{ id:String(id),age:Number(p.age||0),pos:p.position,value:dynastyValue(String(id)),starter:(r.starters||[]).includes(id)||(r.starters||[]).includes(String(id))}}).filter(x=>['QB','RB','WR','TE'].includes(x.pos)&&x.value>0)}
function weightedAge(r,startersOnly=false){const rows=fantasyAges(r).filter(x=>!startersOnly||x.starter);const den=rows.reduce((a,x)=>a+x.value,0);return den?rows.reduce((a,x)=>a+x.age*x.value,0)/den:0}
function positionValue(r,pos){return fantasyAges(r).filter(x=>x.pos===pos).reduce((a,x)=>a+x.value,0)}
function youngCoreValue(r){return fantasyAges(r).filter(x=>x.age&&x.age<=25).reduce((a,x)=>a+x.value,0)}
function veteranValue(r){return fantasyAges(r).filter(x=>x.age>=29).reduce((a,x)=>a+x.value,0)}
function outlookRows(){const base=S.rosters.map(r=>({r,roster:rosterValue(r),starters:starterValue(r),picks:draftCapitalValue(r.roster_id),age:weightedAge(r),starterAge:weightedAge(r,true),young:youngCoreValue(r),vets:veteranValue(r),qb:positionValue(r,'QB'),rb:positionValue(r,'RB'),wr:positionValue(r,'WR'),te:positionValue(r,'TE')}));
 const max=k=>Math.max(...base.map(x=>x[k]),1),minAge=Math.min(...base.map(x=>x.age||99)),maxAge=Math.max(...base.map(x=>x.age||0));
 base.forEach(x=>{x.now=(x.starters/max('starters'))*65+(Number(pts(x.r))/Math.max(...base.map(y=>Number(pts(y.r))),1))*20+(x.roster/max('roster'))*15;x.future=(x.young/max('young'))*45+(x.picks/max('picks'))*35+(x.roster/max('roster'))*20;const aDen=Math.max(maxAge-minAge,.1);x.youth=100-((x.age-minAge)/aDen)*100;});
 base.forEach(x=>{const n=x.now,f=x.future;if(n>=72&&f>=62)x.label='Dynasty Powerhouse';else if(n>=72)x.label='Win Now';else if(f>=72&&n<62)x.label='Ascending';else if(f>=60&&n>=55)x.label='Balanced';else if(f<48&&n<55)x.label='Rebuild';else if(n<60&&x.picks>=max('picks')*.65)x.label='Retooling';else x.label='Middle Ground';x.window=(n*.55+f*.45)});return base.sort((a,b)=>b.window-a.window)}
function labelClass(l){return 'outlook-'+l.toLowerCase().replace(/[^a-z]+/g,'-')}
function matrixPanel(){const rows=outlookRows();return `<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">DYNASTY WINDOW</div><h2>Franchise Matrix</h2></div><p class="muted">Current strength versus long-term flexibility. Click any franchise to open its full team page.</p></div><div class="outlook-grid">${rows.map((x,i)=>`<button class="card outlook-card" onclick="openTeam(${x.r.roster_id})"><div class="outlook-rank">#${i+1}</div><div class="grow"><h3>${esc(name(x.r))}</h3><span class="outlook-label ${labelClass(x.label)}">${esc(x.label)}</span></div><div class="outlook-scores"><span><small>NOW</small><b>${x.now.toFixed(0)}</b></span><span><small>FUTURE</small><b>${x.future.toFixed(0)}</b></span></div></button>`).join('')}</div><div class="card methodology"><h3>What the labels mean</h3><p class="muted">“Now” emphasizes starter value and current production. “Future” emphasizes young-core value, draft capital and total roster value. The labels are relative to this league, so they update automatically as rosters and values change.</p></div></div>`}
function positionsPanel(){const rows=outlookRows();const maxPos={QB:Math.max(...rows.map(x=>x.qb),1),RB:Math.max(...rows.map(x=>x.rb),1),WR:Math.max(...rows.map(x=>x.wr),1),TE:Math.max(...rows.map(x=>x.te),1)};const cell=(v,m)=>{const pct=Math.round(v/m*100);return `<div class="pos-strength"><div class="strength-bar"><i style="width:${Math.max(3,pct)}%"></i></div><span>${fmt(v)}</span></div>`};return `<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">POSITIONAL CAPITAL</div><h2>Strengths & Weaknesses</h2></div><p class="muted">Position value is measured against the strongest room in this league.</p></div><div class="card table-wrap"><table class="table"><thead><tr><th>Franchise</th><th>QB</th><th>RB</th><th>WR</th><th>TE</th><th>Weighted Age</th></tr></thead><tbody>${rows.map(x=>`<tr class="clickable" onclick="openTeam(${x.r.roster_id})"><td><strong>${esc(name(x.r))}</strong></td><td>${cell(x.qb,maxPos.QB)}</td><td>${cell(x.rb,maxPos.RB)}</td><td>${cell(x.wr,maxPos.WR)}</td><td>${cell(x.te,maxPos.TE)}</td><td>${x.age?x.age.toFixed(1):'—'}</td></tr>`).join('')}</tbody></table></div></div>`}
function windowsPanel(){const rows=outlookRows();return `<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">TEAM-BUILDING SIGNALS</div><h2>Window Analysis</h2></div><p class="muted">A roster-age and asset breakdown to help identify likely buyers, sellers and rebuilders.</p></div><div class="grid grid-2">${rows.map(x=>{const youngPct=x.roster?x.young/x.roster*100:0,veteranPct=x.roster?x.vets/x.roster*100:0;let note=x.label==='Win Now'?'Should prioritize points and consolidation over distant picks.':x.label==='Rebuild'?'Best positioned to convert aging value into picks and younger assets.':x.label==='Ascending'?'Young roster with room to accelerate if the standings cooperate.':x.label==='Dynasty Powerhouse'?'Strong present and future profile; no obvious need to force moves.':'Roster is between clear windows; targeted upgrades or asset consolidation could create direction.';return `<div class="card window-card"><div class="trade-head"><div><div class="eyebrow">${esc(x.label.toUpperCase())}</div><h3>${esc(name(x.r))}</h3></div><span class="score-pill">${x.window.toFixed(0)}</span></div><div class="window-metrics"><span><small>Weighted age</small><b>${x.age?x.age.toFixed(1):'—'}</b></span><span><small>Young-core value</small><b>${fmt(x.young)}</b></span><span><small>Veteran value</small><b>${fmt(x.vets)}</b></span><span><small>Draft capital</small><b>${fmt(x.picks)}</b></span></div><div class="age-mix"><div><span>Young core</span><b>${youngPct.toFixed(0)}%</b></div><div><span>29+ value</span><b>${veteranPct.toFixed(0)}%</b></div></div><p class="muted outlook-note">${esc(note)}</p></div>`}).join('')}</div></div>`}
function outlookView(){const rows=outlookRows(),powers=rows.filter(x=>x.label==='Dynasty Powerhouse'||x.label==='Win Now').length,rebuilds=rows.filter(x=>x.label==='Rebuild'||x.label==='Retooling').length,young=[...rows].sort((a,b)=>a.age-b.age)[0];const tabs=[{id:'matrix',label:'Franchise Matrix'},{id:'positions',label:'Position Strengths'},{id:'windows',label:'Window Analysis'}];const panel=outlookTab==='positions'?positionsPanel():outlookTab==='windows'?windowsPanel():matrixPanel();return `<div class="grid grid-3 section-summary">${card('Contenders',powers,'Win-now profiles')}${card('Rebuild / Retool',rebuilds,'Future-focused profiles')}${card('Youngest Core',young?name(young.r):'—',young?.age?`${young.age.toFixed(1)} weighted age`:'')}</div>${innerNav(tabs,outlookTab,'setOutlookTab')}${panel}${attribution()}`}
const outlookBaseRender=render;render=function(){if(S.view==='outlook'){$('#pageTitle').textContent='Franchise Outlook';root.innerHTML=outlookView();return}outlookBaseRender()};window.render=render;
