let matchupTab='scoreboard',matchupFocus=null;
function setMatchupTab(id){matchupTab=id;render();window.scrollTo({top:0,behavior:'smooth'})}
function focusMatchup(id){matchupFocus=Number(id);matchupTab='analyzer';render();window.scrollTo({top:0,behavior:'smooth'})}
window.setMatchupTab=setMatchupTab;window.focusMatchup=focusMatchup;
function matchupGroups(){const g={};(S.matchups||[]).forEach(m=>(g[m.matchup_id]??=[]).push(m));return Object.entries(g).map(([id,rows])=>({id:Number(id),rows})).filter(x=>x.rows.length)}
function starterIds(m){return (roster(m.roster_id)?.starters||[]).filter(Boolean)}
function starterDynastyValue(m){return starterIds(m).reduce((a,id)=>a+dynastyValue(id),0)}
function benchPoints(m){const r=roster(m.roster_id),starts=new Set(r?.starters||[]),pp=m.players_points||{};return Object.entries(pp).filter(([id])=>!starts.has(id)).reduce((a,[,v])=>a+Number(v||0),0)}
function topStarter(m){const pp=m.players_points||{},ids=starterIds(m);return ids.map(id=>({id,pts:Number(pp[id]||0)})).sort((a,b)=>b.pts-a.pts)[0]||null}
function scoreboardPanel(){const groups=matchupGroups();if(!groups.length)return '<div class="card muted">No matchup data is available yet for this week.</div>';return `<div class="matchup-score-grid">${groups.map(x=>{const a=x.rows[0],b=x.rows[1],ra=roster(a.roster_id),rb=roster(b?.roster_id);const ap=Number(a.points||0),bp=Number(b?.points||0),lead=ap===bp?0:ap>bp?1:2;return `<button class="card score-card" onclick="focusMatchup(${x.id})"><div class="score-card-head"><span class="eyebrow">MATCHUP ${x.id}</span><span class="badge">ANALYZE →</span></div><div class="score-team ${lead===1?'leading':''}"><div><strong>${esc(name(ra))}</strong><small>${rec(ra)}</small></div><b>${ap.toFixed(2)}</b></div><div class="score-divider">VS</div><div class="score-team ${lead===2?'leading':''}"><div><strong>${esc(name(rb))}</strong><small>${rb?rec(rb):'—'}</small></div><b>${bp.toFixed(2)}</b></div></button>`}).join('')}</div>`}
function playerLine(id,ptsVal){const p=player(id);return `<div class="starter-line"><span class="${posClass(p.position)}">${esc(p.position||'—')}</span><div class="grow"><strong>${esc(pname(id))}</strong><small>${esc(p.team||'FA')} · Dynasty ${fmt(dynastyValue(id))}</small></div><b>${Number(ptsVal||0).toFixed(2)}</b></div>`}
function teamAnalyzer(m){const r=roster(m.roster_id),pp=m.players_points||{},ids=starterIds(m),top=topStarter(m);return `<div class="card matchup-team-analysis"><div class="analysis-team-head">${teamLogo(r)}<div class="grow"><div class="eyebrow">${rec(r)}</div><h3>${esc(name(r))}</h3></div><div class="analysis-score">${Number(m.points||0).toFixed(2)}</div></div><div class="analysis-metrics"><div><span>Starter Value</span><strong>${fmt(starterDynastyValue(m))}</strong></div><div><span>Bench Points</span><strong>${benchPoints(m).toFixed(2)}</strong></div><div><span>Top Starter</span><strong>${top?esc(pname(top.id)):'—'}</strong></div></div><div class="starter-list">${ids.map(id=>playerLine(id,pp[id])).join('')}</div></div>`}
function analyzerPanel(){const groups=matchupGroups();if(!groups.length)return scoreboardPanel();if(!matchupFocus||!groups.some(x=>x.id===matchupFocus))matchupFocus=groups[0].id;const selected=groups.find(x=>x.id===matchupFocus);return `<div class="matchup-selector">${groups.map(x=>`<button class="${x.id===matchupFocus?'active':''}" onclick="focusMatchup(${x.id})">Matchup ${x.id}</button>`).join('')}</div><div class="grid grid-2 analyzer-grid">${selected.rows.map(teamAnalyzer).join('')}</div><div class="card methodology"><h3>Matchup read</h3><p class="muted">Live score comes from Sleeper. Starter dynasty value is a roster-strength context metric, not a point projection. Bench points show how much scoring is currently outside the starting lineup.</p></div>`}
function playoffPanel(){const rows=standings(),playoffTeams=Math.min(Number(S.league.settings?.playoff_teams||6),rows.length);return `<div class="card table-wrap"><table class="table"><thead><tr><th>Seed</th><th>Franchise</th><th>Record</th><th>PF</th><th>Dynasty Power</th><th>Status</th></tr></thead><tbody>${rows.map((r,i)=>{const p=powerRankings().find(x=>x.r.roster_id===r.roster_id);return `<tr class="clickable" onclick="openTeam(${r.roster_id})"><td class="rank">${i+1}</td><td><strong>${esc(name(r))}</strong></td><td>${rec(r)}</td><td>${pts(r)}</td><td>${p?p.score.toFixed(1):'—'}</td><td><span class="playoff-status ${i<playoffTeams?'in':''}">${i<playoffTeams?'PLAYOFF POSITION':'OUTSIDE'}</span></td></tr>`}).join('')}</tbody></table></div><div class="card methodology"><h3>Playoff picture</h3><p class="muted">This reflects current Sleeper standings and the league's configured playoff-team count. Early in the season it is a snapshot, not a playoff probability model.</p></div>`}
function matchupCenterView(){const groups=matchupGroups(),highest=groups.flatMap(x=>x.rows).sort((a,b)=>Number(b.points||0)-Number(a.points||0))[0];const tabs=[{id:'scoreboard',label:'Weekly Scoreboard'},{id:'analyzer',label:'Matchup Analyzer'},{id:'playoffs',label:'Playoff Picture'}];const panel=matchupTab==='analyzer'?analyzerPanel():matchupTab==='playoffs'?playoffPanel():scoreboardPanel();return `<div class="grid grid-3 section-summary">${card('Week',S.league.settings?.leg||1,'Sleeper matchup week')}${card('Matchups',groups.length,'Current slate')}${card('High Score',highest?Number(highest.points||0).toFixed(2):'—',highest?name(roster(highest.roster_id)):'No score yet')}</div>${innerNav(tabs,matchupTab,'setMatchupTab')}${panel}`}
const matchupBaseRender=render;
render=function(){if(S.view==='matchups'){$('#pageTitle').textContent='Matchup Center';root.innerHTML=matchupCenterView();return}matchupBaseRender()};
window.render=render;
