let playerProfileID=null,playerProfileFrom='values',playerNewsCache={};
function playerOwner(id){return S.rosters.find(r=>(r.players||[]).includes(String(id))||(r.players||[]).includes(id))||null}
function playerRole(id,r){if(!r)return'Free Agent';if((r.starters||[]).includes(id)|| (r.starters||[]).includes(String(id)))return'Starter';if((r.reserve||[]).includes(id)||(r.reserve||[]).includes(String(id)))return'IR';if((r.taxi||[]).includes(id)||(r.taxi||[]).includes(String(id)))return'Taxi';return'Bench'}
function playerTransactions(id){return(S.tx||[]).filter(t=>Object.prototype.hasOwnProperty.call(t.adds||{},id)||Object.prototype.hasOwnProperty.call(t.drops||{},id)).slice(0,12)}
function playerSportsbookProps(id){const n=(pname(id)||'').toLowerCase();const out=[];(sportsbookData?.events||[]).forEach(e=>(e.props||[]).forEach(p=>{if((p.playerName||'').toLowerCase()===n)out.push({event:e,prop:p})}));return out.slice(0,12)}
function playerKtcUrl(id){return 'https://keeptradecut.com/dynasty-rankings/players/'+encodeURIComponent((pname(id)||'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''))}
async function ensurePlayerNews(id){if(playerNewsCache[id])return;if(!pname(id))return;playerNewsCache[id]={loading:true,items:[]};if(S.view==='player')render();try{const r=await fetch('/api/player-news?q='+encodeURIComponent(pname(id)));const d=await r.json();playerNewsCache[id]={loading:false,items:d.items||[]}}catch{playerNewsCache[id]={loading:false,items:[]}}if(S.view==='player'&&String(playerProfileID)===String(id))render()}
function openPlayer(id,from){playerProfileID=String(id);playerProfileFrom=from||S.view||'values';S.view='player';document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));render();window.scrollTo({top:0,behavior:'smooth'});setTimeout(()=>ensurePlayerNews(playerProfileID),0);if(typeof sportsbookData!=='undefined'&&!sportsbookData&&!sportsbookLoading)setTimeout(loadSportsbook,0)}
function closePlayer(){const dest=playerProfileFrom==='player'?'values':playerProfileFrom;go(dest)}
window.openPlayer=openPlayer;window.closePlayer=closePlayer;
function playerHeadshot(id){const p=player(id),src=p?.fantasy_data_id?null:`https://sleepercdn.com/content/nfl/players/${id}.jpg`;return src?`<img class="player-headshot" src="${src}" onerror="this.style.display='none'" alt="">`:`<div class="player-headshot fallback">${esc((p.position||'NFL').slice(0,3))}</div>`}
function valueRank(id){const ids=Object.keys(S.values||{}).sort((a,b)=>dynastyValue(b)-dynastyValue(a));const i=ids.indexOf(String(id));return i>=0?i+1:null}
function positionRank(id){const pos=player(id).position,ids=Object.keys(S.values||{}).filter(x=>player(x).position===pos).sort((a,b)=>dynastyValue(b)-dynastyValue(a));const i=ids.indexOf(String(id));return i>=0?i+1:null}
function profileOverview(id){const p=player(id),r=playerOwner(id),role=playerRole(id,r),vr=valueRank(id),pr=positionRank(id);return `<div class="player-hero card">${playerHeadshot(id)}<div class="grow"><div class="eyebrow">PLAYER PROFILE</div><h2>${esc(pname(id))}</h2><div class="player-meta"><span class="${posClass(p.position)}">${esc(p.position||'—')}</span><span>${esc(p.team||'FA')}</span>${p.age?`<span>Age ${esc(p.age)}</span>`:''}${p.years_exp!==undefined?`<span>${esc(p.years_exp)} yrs exp.</span>`:''}</div><div class="player-owner-line">${r?`Owned by <button onclick="openTeam(${r.roster_id})">${esc(name(r))}</button> · ${esc(role)}`:'Unrostered in your league'}</div></div><div class="player-value-block"><small>Dynasty Value</small><strong>${fmt(dynastyValue(id))}</strong><span>${vr?`#${vr} overall`:''}${pr?` · ${p.position}${pr}`:''}</span></div></div><div class="grid grid-4 player-kpis">${card('Current Value',fmt(dynastyValue(id)),currentFormat())}${card('Overall Rank',vr?`#${vr}`:'—','Dynasty market')}${card('Position Rank',pr?`${p.position}${pr}`:'—',p.position||'')}${card('League Status',r?role:'Free Agent',r?name(r):'Available')}</div>`}
function profileHistory(id){const tx=playerTransactions(id);if(!tx.length)return `<div class="card muted">No current-season transactions involving ${esc(pname(id))} were found.</div>`;return `<div class="card table-wrap"><table class="table"><thead><tr><th>Date</th><th>Type</th><th>Movement</th></tr></thead><tbody>${tx.map(t=>{const add=t.adds?.[id],drop=t.drops?.[id];let movement='';if(add)movement=`Added by ${name(roster(add))}`;if(drop)movement+=(movement?' · ':'')+`Dropped by ${name(roster(drop))}`;return `<tr><td>${date(t.created)}</td><td>${esc(t.type||'transaction')}</td><td>${esc(movement||'Roster movement')}</td></tr>`}).join('')}</tbody></table></div>`}
function profileNews(id){const n=playerNewsCache[id];if(!n||n.loading)return `<div class="card"><strong>Loading current NFL news…</strong></div>`;if(!n.items.length)return `<div class="card muted">No recent news articles found.</div>`;return `<div class="news-list">${n.items.map(x=>`<a class="card news-item" href="${esc(x.link)}" target="_blank" rel="noopener noreferrer"><div><strong>${esc(x.title)}</strong><small>${esc(x.source||'News')} · ${x.published?new Date(x.published).toLocaleDateString():''}</small></div><span>↗</span></a>`).join('')}</div>`}
function profileProps(id){const rows=playerSportsbookProps(id);if(!rows.length)return `<div class="card muted">No sportsbook props are currently posted for ${esc(pname(id))}. Lines usually populate closer to kickoff.</div>`;return `<div class="sportsbook-events">${rows.map(x=>`<div class="card profile-prop"><div><strong>${esc(statLabel(x.prop.statID))}</strong><small>${esc(x.event.away)} @ ${esc(x.event.home)} · ${(x.prop.side||'').toUpperCase()} ${x.prop.consensusLine??''}</small></div><div class="book-odds-grid">${['draftkings','fanduel','betmgm','caesars'].map(b=>{const v=x.prop.byBookmaker?.[b];return `<div class="book-odd"><span>${bookLabel(b)}</span><strong>${v?oddsVal(v.odds):'—'}</strong></div>`}).join('')}</div></div>`).join('')}</div>`}
function profileView(){const id=playerProfileID,p=player(id);if(!id||!p)return'<div class="card">Player not found.</div>';const tabs=[{id:'overview',label:'Overview'},{id:'news',label:'News'},{id:'history',label:'League History'},{id:'props',label:'Sportsbook Props'}];const active=window.playerProfileTab||'overview';let panel=active==='news'?profileNews(id):active==='history'?profileHistory(id):active==='props'?profileProps(id):`${profileOverview(id)}<div class="profile-actions card"><a href="${playerKtcUrl(id)}" target="_blank" rel="noopener noreferrer">View on KeepTradeCut ↗</a>${playerOwner(id)?`<button onclick="openTeam(${playerOwner(id).roster_id})">Open ${esc(name(playerOwner(id)))} →</button>`:''}</div>`;return `<button class="back-btn" onclick="closePlayer()">← Back</button>${innerNav(tabs,active,'setPlayerProfileTab')}${panel}${attribution()}`}
function setPlayerProfileTab(id){window.playerProfileTab=id;render();if(id==='news')ensurePlayerNews(playerProfileID);if(id==='props'&&typeof sportsbookData!=='undefined'&&!sportsbookData&&!sportsbookLoading)loadSportsbook()}
window.setPlayerProfileTab=setPlayerProfileTab;
const oldRosterRows=rosterRows;rosterRows=function(ids=[],r){const starters=new Set(r.starters||[]),reserve=new Set(r.reserve||[]),taxi=new Set(r.taxi||[]);return ids.map(id=>{const p=player(id);let role=starters.has(id)?'Starter':reserve.has(id)?'IR':taxi.has(id)?'Taxi':'Bench';return `<tr class="clickable" onclick="openPlayer('${id}','teams')"><td><span class="${posClass(p.position)}">${esc(p.position||'—')}</span></td><td><strong>${esc(pname(id))}</strong></td><td>${esc(p.team||'FA')}</td><td>${fmt(dynastyValue(id))}</td><td><span class="role role-${role.toLowerCase()}">${role}</span></td></tr>`}).join('')};
const playerCenterBaseRender=render;render=function(){if(S.view==='player'){$('#pageTitle').textContent=pname(playerProfileID);root.innerHTML=profileView();return}playerCenterBaseRender()};window.render=render;
