let playoffTab='picture',playoffData=null,playoffLoading=false;
function setPlayoffTab(id){playoffTab=id;render();window.scrollTo({top:0,behavior:'smooth'})}window.setPlayoffTab=setPlayoffTab;
async function ensurePlayoffData(){if(playoffData||playoffLoading)return;playoffLoading=true;if(S.view==='playoffs')render();const lid=S.league.league_id;const [winners,losers]=await Promise.all([safe(`/league/${lid}/winners_bracket`,[]),safe(`/league/${lid}/losers_bracket`,[])]);playoffData={winners,losers};playoffLoading=false;if(S.view==='playoffs')render()}
function playoffTeams(){const n=Number(S.league.settings?.playoff_teams||6);return standings().map((r,i)=>({r,seed:i+1,in:i<n}));}
function playoffPicturePanel(){const rows=playoffTeams(),n=Number(S.league.settings?.playoff_teams||6);return `<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">POSTSEASON FIELD</div><h2>Playoff Picture</h2></div><p class="muted">Current seeding uses the live Sleeper standings. ${n} teams make the playoff field.</p></div><div class="card table-wrap"><table class="table"><thead><tr><th>Seed</th><th>Franchise</th><th>Record</th><th>PF</th><th>Status</th></tr></thead><tbody>${rows.map(x=>`<tr class="clickable" onclick="openTeam(${x.r.roster_id})"><td class="rank">${x.seed}</td><td><strong>${esc(name(x.r))}</strong></td><td>${rec(x.r)}</td><td>${pts(x.r)}</td><td><span class="role ${x.in?'playoff-in':'playoff-out'}">${x.in?'IN':'OUT'}</span></td></tr>`).join('')}</tbody></table></div></div>`}
function bracketName(id){return name(roster(id))}
function bracketPanel(){if(playoffLoading)return'<div class="card">Loading Sleeper playoff bracket…</div>';const b=playoffData?.winners||[];if(!b.length)return'<div class="card muted">The current-season playoff bracket is not available yet. It will populate automatically when Sleeper creates it.</div>';const rounds=[...new Set(b.map(x=>Number(x.r||1)))].sort((a,b)=>a-b);return `<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">SLEEPER BRACKET</div><h2>Championship Bracket</h2></div></div><div class="bracket-grid">${rounds.map(rd=>`<div class="bracket-round"><h3>Round ${rd}</h3>${b.filter(x=>Number(x.r||1)===rd).map(g=>`<div class="card bracket-game"><span class="${g.w===g.t1?'winner':''}">${esc(bracketName(g.t1))}</span><span class="${g.w===g.t2?'winner':''}">${esc(bracketName(g.t2))}</span></div>`).join('')}</div>`).join('')}</div></div>`}
function consolationPanel(){if(playoffLoading)return bracketPanel();const b=playoffData?.losers||[];if(!b.length)return'<div class="card muted">No consolation/toilet-bowl bracket is available yet.</div>';return `<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">CONSOLATION</div><h2>Toilet Bowl / Consolation</h2></div></div><div class="grid grid-2">${b.map(g=>`<div class="card bracket-game"><small>Round ${g.r||'—'}</small><span class="${g.w===g.t1?'winner':''}">${esc(bracketName(g.t1))}</span><span class="${g.w===g.t2?'winner':''}">${esc(bracketName(g.t2))}</span></div>`).join('')}</div></div>`}
function championshipHistoryPanel(){if(typeof ensureHistory==='function'&&!historyLoaded){setTimeout(ensureHistory,0);return'<div class="card">Loading championship history…</div>'}const rows=(typeof HIST!=='undefined'?HIST:[]).filter(x=>x.champ);return `<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">LEAGUE CHAMPIONS</div><h2>Championship History</h2></div></div><div class="history-season-grid">${rows.map(x=>`<div class="card season-card"><div class="season-year">${esc(x.league.season)}</div><div class="champion-line"><span>🏆</span><div><small>Champion</small><strong>${esc(x.champ)}</strong></div></div>${x.runner?`<div class="history-meta"><span>Runner-up</span><strong>${esc(x.runner)}</strong></div>`:''}</div>`).join('')||'<div class="card muted">Championship results will appear when linked season brackets are available.</div>'}</div></div>`}
function playoffView(){setTimeout(ensurePlayoffData,0);const tabs=[{id:'picture',label:'Playoff Picture'},{id:'bracket',label:'Championship Bracket'},{id:'consolation',label:'Consolation'},{id:'history',label:'Championship History'}];const p=playoffTab==='bracket'?bracketPanel():playoffTab==='consolation'?consolationPanel():playoffTab==='history'?championshipHistoryPanel():playoffPicturePanel();return `<div class="grid grid-3 section-summary">${card('Playoff Teams',S.league.settings?.playoff_teams||6,'League setting')}${card('Current Week',S.league.settings?.leg||1,'Sleeper season state')}${card('Championships',typeof HIST!=='undefined'&&historyLoaded?HIST.filter(x=>x.champ).length:'…','Linked seasons')}</div>${innerNav(tabs,playoffTab,'setPlayoffTab')}${p}`}
const playoffBaseRender=render;render=function(){if(S.view==='playoffs'){$('#pageTitle').textContent='Playoffs & Championships';root.innerHTML=playoffView();return}playoffBaseRender()};window.render=render;