let playerProfileID=null,playerProfileFrom='teams',playerProfileTab='overview';
function playerOwner(id){return S.rosters.find(r=>(r.players||[]).map(String).includes(String(id)))||null}
function playerRole(id,r){if(!r)return'Free Agent';const sid=String(id);if((r.starters||[]).map(String).includes(sid))return'Starter';if((r.reserve||[]).map(String).includes(sid))return'IR';if((r.taxi||[]).map(String).includes(sid))return'Taxi';return'Bench'}
function openPlayer(id,from='teams'){playerProfileID=String(id);playerProfileFrom=from;playerProfileTab='overview';S.view='player';document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));render();window.scrollTo(0,0)}
function closePlayer(){go(playerProfileFrom==='player'?'teams':playerProfileFrom)}
window.openPlayer=openPlayer;window.closePlayer=closePlayer;
function setPlayerProfileTab(id){playerProfileTab=id;render()}
window.setPlayerProfileTab=setPlayerProfileTab;
function playerKtcUrl(id){return 'https://keeptradecut.com/dynasty-rankings/players/'+encodeURIComponent((pname(id)||'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''))}
function playerTransactions(id){return(S.tx||[]).filter(t=>Object.prototype.hasOwnProperty.call(t.adds||{},id)||Object.prototype.hasOwnProperty.call(t.drops||{},id)).slice(0,12)}
function profileOverview(id){const p=player(id),r=playerOwner(id),role=playerRole(id,r);return `<div class="player-hero card"><div class="player-headshot fallback">${esc((p.position||'NFL').slice(0,3))}</div><div class="grow"><div class="eyebrow">PLAYER PROFILE</div><h2>${esc(pname(id))}</h2><div class="player-meta"><span class="${posClass(p.position)}">${esc(p.position||'—')}</span><span>${esc(p.team||'FA')}</span>${p.age?`<span>Age ${esc(p.age)}</span>`:''}</div><div class="player-owner-line">${r?`Owned by <button type="button" onclick="openTeam(${r.roster_id})">${esc(name(r))}</button> · ${esc(role)}`:'Unrostered in your league'}</div></div><div class="player-value-block"><small>Dynasty Value</small><strong>${fmt(dynastyValue(id))}</strong><span>${currentFormat()}</span></div></div><div class="grid grid-3 player-kpis">${card('Current Value',fmt(dynastyValue(id)),currentFormat())}${card('NFL Team',p.team||'FA',p.position||'')}${card('League Status',r?role:'Free Agent',r?name(r):'Available')}</div><div class="profile-actions card"><a href="${playerKtcUrl(id)}" target="_blank" rel="noopener noreferrer">View on KeepTradeCut ↗</a>${r?`<button type="button" onclick="openTeam(${r.roster_id})">Open ${esc(name(r))} →</button>`:''}</div>`}
function profileHistory(id){const tx=playerTransactions(id);if(!tx.length)return `<div class="card muted">No current-season transactions involving ${esc(pname(id))} were found.</div>`;return `<div class="card table-wrap"><table class="table"><thead><tr><th>Date</th><th>Type</th><th>Movement</th></tr></thead><tbody>${tx.map(t=>{const add=t.adds?.[id],drop=t.drops?.[id];let movement='';if(add)movement=`Added by ${name(roster(add))}`;if(drop)movement+=(movement?' · ':'')+`Dropped by ${name(roster(drop))}`;return `<tr><td>${date(t.created)}</td><td>${esc(t.type||'transaction')}</td><td>${esc(movement||'Roster movement')}</td></tr>`}).join('')}</tbody></table></div>`}
function profileProps(id){if(typeof sportsbookData==='undefined'||!sportsbookData)return `<div class="card muted">Sportsbook data will load from the Sportsbook section when available.</div>`;const n=(pname(id)||'').toLowerCase(),rows=[];(sportsbookData.events||[]).forEach(e=>(e.props||[]).forEach(p=>{if((p.playerName||'').toLowerCase()===n)rows.push({e,p})}));if(!rows.length)return `<div class="card muted">No sportsbook props are currently posted for ${esc(pname(id))}.</div>`;return `<div class="sportsbook-events">${rows.slice(0,12).map(x=>`<div class="card profile-prop"><strong>${esc(typeof statLabel==='function'?statLabel(x.p.statID):x.p.statID)}</strong><small>${esc(x.e.away)} @ ${esc(x.e.home)}</small></div>`).join('')}</div>`}
function profileView(){const id=playerProfileID;if(!id)return'<div class="card">Player not found.</div>';const tabs=[{id:'overview',label:'Overview'},{id:'history',label:'League History'},{id:'props',label:'Sportsbook Props'}];const panel=playerProfileTab==='history'?profileHistory(id):playerProfileTab==='props'?profileProps(id):profileOverview(id);return `<button class="back-btn" type="button" onclick="closePlayer()">← Back</button>${innerNav(tabs,playerProfileTab,'setPlayerProfileTab')}${panel}${attribution()}`}
const originalRosterRows=rosterRows;
rosterRows=function(ids=[],r){const starters=new Set((r.starters||[]).map(String)),reserve=new Set((r.reserve||[]).map(String)),taxi=new Set((r.taxi||[]).map(String));return ids.map(raw=>{const id=String(raw),p=player(id);let role=starters.has(id)?'Starter':reserve.has(id)?'IR':taxi.has(id)?'Taxi':'Bench';return `<tr><td><span class="${posClass(p.position)}">${esc(p.position||'—')}</span></td><td><button type="button" class="player-name-link" onclick="openPlayer('${esc(id)}','teams')"><strong>${esc(pname(id))}</strong><span>View profile →</span></button></td><td>${esc(p.team||'FA')}</td><td>${fmt(dynastyValue(id))}</td><td><span class="role role-${role.toLowerCase()}">${role}</span></td></tr>`}).join('')};
const playerCenterRender=render;
render=function(){if(S.view==='player'){$('#pageTitle').textContent=pname(playerProfileID);root.innerHTML=profileView();return}playerCenterRender()};
window.render=render;
