const PROSPECTS=[
 {rank:1,name:'Jeremiah Smith',pos:'WR',school:'Ohio State',tier:'Elite',note:'Prototype alpha WR and the early fantasy prize of the class.'},
 {rank:2,name:'Ryan Williams',pos:'WR',school:'Alabama',tier:'Elite',note:'Explosive separator with true game-breaking upside.'},
 {rank:3,name:'Julian Sayin',pos:'QB',school:'Ohio State',tier:'Round 1',note:'High-end accuracy and processing profile in a premium offense.'},
 {rank:4,name:'Dante Moore',pos:'QB',school:'Oregon',tier:'Round 1',note:'Arm talent and NFL traits make him a major Superflex target.'},
 {rank:5,name:'Arch Manning',pos:'QB',school:'Texas',tier:'Round 1',note:'Premium physical tools with enormous dynasty-market attention.'},
 {rank:6,name:'Dylan Raiola',pos:'QB',school:'Nebraska',tier:'Round 1-2',note:'Big-arm passer whose 2026 development can move him dramatically.'},
 {rank:7,name:'Nate Frazier',pos:'RB',school:'Georgia',tier:'Day 2+',note:'Power/explosion blend with a path to lead-back draft capital.'},
 {rank:8,name:'Cam Coleman',pos:'WR',school:'Auburn',tier:'Day 1-2',note:'Size, ball skills and early production keep the ceiling high.'},
 {rank:9,name:'Jordan Seaton',pos:'OT',school:'Colorado',tier:'NFL Elite',note:'Not a fantasy pick, but one of the premier overall 2027 prospects.'},
 {rank:10,name:'KJ Bolden',pos:'S',school:'Georgia',tier:'NFL Round 1',note:'IDP name to know with high-end athletic and coverage traits.'},
 {rank:11,name:'Sammy Brown',pos:'LB',school:'Clemson',tier:'IDP',note:'Impact linebacker with strong IDP upside if the league adds it.'},
 {rank:12,name:'Jerrick Gibson',pos:'RB',school:'Texas',tier:'Watch',note:'Backfield opportunity and 2026 usage will drive his rookie-stock trajectory.'}
];
let selectedProspect='Jeremiah Smith';
function prospectHubHtml(){return `<div class="section-title"><h2>2027 Prospect Hub</h2><span class="badge">COLLEGE WATCHLIST</span></div><div class="prospect-layout"><div class="card prospect-board"><div class="prospect-head"><div><div class="eyebrow">FANTASY-FOCUSED WATCHLIST</div><h3>2027 Big Board</h3></div><span class="badge">PRESEASON · SUBJECT TO CHANGE</span></div><div class="prospect-list">${PROSPECTS.map(p=>`<button class="prospect-row ${p.name===selectedProspect?'selected':''}" onclick="selectProspect('${p.name.replace(/'/g,"\\'")}')"><span class="prospect-rank">${p.rank}</span><span class="pos ${posClass(p.pos)}">${p.pos}</span><span class="prospect-name"><strong>${esc(p.name)}</strong><small>${esc(p.school)}</small></span><span class="prospect-tier">${esc(p.tier)}</span></button>`).join('')}</div><p class="fineprint">This is a League HQ watchlist, not a claim about final NFL Draft order. It is intentionally fantasy-weighted, so QBs/RBs/WRs receive more emphasis than an NFL-only big board.</p></div><div class="card prospect-news"><div class="prospect-head"><div><div class="eyebrow">LIVE NEWS TRACKER</div><h3 id="prospectNewsTitle">${esc(selectedProspect)}</h3></div><button class="icon-btn" onclick="loadProspectNews(selectedProspect)" title="Refresh news">↻</button></div><div id="prospectNews"><div class="muted news-loading">Select a prospect to load current coverage.</div></div></div></div>`}
const baseDraft=draft;
draft=function(){const html=baseDraft();setTimeout(()=>loadProspectNews(selectedProspect),0);return html+prospectHubHtml()}
async function loadProspectNews(q){const box=document.querySelector('#prospectNews');if(!box)return;box.innerHTML='<div class="muted news-loading">Loading current coverage…</div>';try{const r=await fetch('/api/prospect-news?q='+encodeURIComponent(q));const data=await r.json();if(!data.items?.length)throw Error('No stories');box.innerHTML=data.items.map(x=>`<a class="news-item" href="${esc(x.link)}" target="_blank" rel="noopener"><strong>${esc(x.title)}</strong><span>${esc(x.source||'College football coverage')} · ${x.published?new Date(x.published).toLocaleDateString(undefined,{month:'short',day:'numeric'}):''}</span></a>`).join('')}catch(e){box.innerHTML='<div class="muted news-loading">Current news is temporarily unavailable. Try refresh again shortly.</div>'}}
function selectProspect(q){selectedProspect=q;document.querySelectorAll('.prospect-row').forEach(x=>x.classList.toggle('selected',x.querySelector('strong')?.textContent===q));const t=document.querySelector('#prospectNewsTitle');if(t)t.textContent=q;loadProspectNews(q)}
window.selectProspect=selectProspect;window.loadProspectNews=loadProspectNews;
