let scheduleTab='league',scheduleLoaded=false,scheduleLoading=false,scheduleWeeks=[],scheduleTeam=null;
function setScheduleTab(id){scheduleTab=id;render();if(!scheduleLoaded&&!scheduleLoading)loadScheduleData()}
function setScheduleTeam(id){scheduleTeam=Number(id);render()}
window.setScheduleTab=setScheduleTab;window.setScheduleTeam=setScheduleTeam;
async function loadScheduleData(){scheduleLoading=true;if(S.view==='schedule')render();try{const playoffStart=Number(S.league?.settings?.playoff_week_start||15),maxWeek=Math.max(18,playoffStart+3);const weeks=await Promise.all(Array.from({length:maxWeek},(_,i)=>safe(`/league/${LEAGUE}/matchups/${i+1}`,[])));scheduleWeeks=weeks.map((rows,i)=>({week:i+1,rows})).filter(x=>x.rows.length);scheduleLoaded=true;if(!scheduleTeam&&S.rosters[0])scheduleTeam=S.rosters[0].roster_id}catch(e){console.warn(e)}finally{scheduleLoading=false;if(S.view==='schedule')render()}}
function weekGroups(rows=[]){const g={};rows.forEach(m=>{if(m.matchup_id===null||m.matchup_id===undefined)return;(g[m.matchup_id]??=[]).push(m)});return Object.values(g).filter(x=>x.length>=2)}
function currentWeekNo(){return Number(S.league?.settings?.leg||1)}
function opponentFor(rid,week){const w=scheduleWeeks.find(x=>x.week===week);if(!w)return null;const mine=w.rows.find(x=>Number(x.roster_id)===Number(rid));if(!mine)return null;return w.rows.find(x=>x.matchup_id===mine.matchup_id&&Number(x.roster_id)!==Number(rid))||null}
function powerMap(){const p=powerRankings();const map=new Map;p.forEach((x,i)=>map.set(Number(x.r.roster_id),{rank:i+1,score:x.score,total:x.total}));return map}
function regularSeasonWeeks(){const ps=Number(S.league?.settings?.playoff_week_start||15);return scheduleWeeks.filter(x=>x.week<ps)}
function sosRows(){const map=powerMap(),cw=currentWeekNo(),weeks=regularSeasonWeeks().filter(x=>x.week>=cw);return S.rosters.map(r=>{const opps=weeks.map(w=>opponentFor(r.roster_id,w.week)).filter(Boolean);const scores=opps.map(o=>map.get(Number(o.roster_id))?.score||0);const avg=scores.length?scores.reduce((a,b)=>a+b,0)/scores.length:0;const top3=opps.filter(o=>(map.get(Number(o.roster_id))?.rank||99)<=3).length;return{r,avg,opps,top3}}).sort((a,b)=>b.avg-a.avg)}
function scheduleSummary(){const rows=sosRows(),hard=rows[0],easy=rows[rows.length-1],ps=Number(S.league?.settings?.playoff_week_start||15);return `<div class="grid grid-4 section-summary">${card('Current Week',currentWeekNo(),`${S.league?.season||2026} season`)}${card('Playoffs Start',`Week ${ps}`,'Sleeper setting')}${card('Hardest Remaining',hard?name(hard.r):'—',hard?`${hard.avg.toFixed(1)} avg opponent power`:'')}${card('Easiest Remaining',easy?name(easy.r):'—',easy?`${easy.avg.toFixed(1)} avg opponent power`:'')}</div>`}
function leagueSchedulePanel(){if(scheduleLoading||!scheduleLoaded)return'<div class="card">Loading full Sleeper schedule…</div>';const weeks=regularSeasonWeeks();return `<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">FULL REGULAR-SEASON SLATE</div><h2>League Schedule</h2></div><p class="muted">Every scheduled matchup by week. Scores appear once games begin.</p></div><div class="schedule-week-grid">${weeks.map(w=>`<div class="card schedule-week"><div class="schedule-week-head"><strong>Week ${w.week}</strong>${w.week===currentWeekNo()?'<span class="badge">CURRENT</span>':''}</div>${weekGroups(w.rows).map(g=>`<div class="schedule-match"><button onclick="openTeam(${g[0].roster_id})">${esc(name(roster(g[0].roster_id)))}</button><span>${Number(g[0].points||0).toFixed(1)} <b>vs</b> ${Number(g[1].points||0).toFixed(1)}</span><button onclick="openTeam(${g[1].roster_id})">${esc(name(roster(g[1].roster_id)))}</button></div>`).join('')}</div>`).join('')}</div></div>`}
function sosPanel(){if(scheduleLoading||!scheduleLoaded)return'<div class="card">Calculating remaining schedule strength…</div>';const rows=sosRows();return `<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">REMAINING SCHEDULE</div><h2>Strength of Schedule</h2></div><p class="muted">Difficulty is based on each remaining opponent's current League HQ power score. Higher means harder.</p></div><div class="card table-wrap"><table class="table"><thead><tr><th>#</th><th>Franchise</th><th>Avg Opp. Power</th><th>Top-3 Opponents</th><th>Games Left</th><th>Next Opponent</th></tr></thead><tbody>${rows.map((x,i)=>{const nxt=x.opps[0];return `<tr class="clickable" onclick="openTeam(${x.r.roster_id})"><td class="rank">${i+1}</td><td><strong>${esc(name(x.r))}</strong></td><td><span class="sos-pill ${i<3?'hard':i>=rows.length-3?'easy':''}">${x.avg.toFixed(1)}</span></td><td>${x.top3}</td><td>${x.opps.length}</td><td>${nxt?esc(name(roster(nxt.roster_id))):'—'}</td></tr>`}).join('')}</tbody></table></div><p class="fineprint">This is a relative schedule-strength index, not a projected win probability. Power scores will move as rosters and draft capital change.</p></div>`}
function teamSchedulePanel(){if(scheduleLoading||!scheduleLoaded)return'<div class="card">Loading team schedules…</div>';const rid=scheduleTeam||S.rosters[0]?.roster_id,r=roster(rid),pm=powerMap(),ps=Number(S.league?.settings?.playoff_week_start||15);const weeks=scheduleWeeks.filter(x=>x.week<ps);return `<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">FRANCHISE SCHEDULE</div><h2>${esc(name(r))}</h2></div><select class="schedule-select" onchange="setScheduleTeam(this.value)">${S.rosters.map(x=>`<option value="${x.roster_id}" ${Number(x.roster_id)===Number(rid)?'selected':''}>${esc(name(x))}</option>`).join('')}</select></div><div class="team-schedule-list">${weeks.map(w=>{const mine=w.rows.find(x=>Number(x.roster_id)===Number(rid)),opp=mine?opponentFor(rid,w.week):null;if(!mine||!opp)return'';const op=pm.get(Number(opp.roster_id)),done=w.week<currentWeekNo()||Number(mine.points||0)>0||Number(opp.points||0)>0;let result='Upcoming';if(done){const a=Number(mine.points||0),b=Number(opp.points||0);result=a>b?'W':a<b?'L':'T'}return `<div class="card team-schedule-row"><div class="week-box">W${w.week}</div><div class="grow"><strong>${esc(name(roster(opp.roster_id)))}</strong><small>Opponent power #${op?.rank||'—'} · ${op?.score?.toFixed(1)||'—'}</small></div><div class="schedule-result ${result==='W'?'win':result==='L'?'loss':''}">${result}${done?` · ${Number(mine.points||0).toFixed(1)}-${Number(opp.points||0).toFixed(1)}`:''}</div></div>`}).join('')}</div></div>`}
function playoffPathPanel(){if(scheduleLoading||!scheduleLoaded)return'<div class="card">Loading playoff path…</div>';const ps=Number(S.league?.settings?.playoff_week_start||15),rows=sosRows(),stand=standings(),playoffTeams=Number(S.league?.settings?.playoff_teams||6);return `<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">ROAD TO THE PLAYOFFS</div><h2>Playoff Path</h2></div><p class="muted">Combines current seeding with remaining schedule difficulty.</p></div><div class="card table-wrap"><table class="table"><thead><tr><th>Seed</th><th>Franchise</th><th>Record</th><th>Status</th><th>Remaining SOS Rank</th><th>Top-3 Opps Left</th></tr></thead><tbody>${stand.map((r,i)=>{const sidx=rows.findIndex(x=>Number(x.r.roster_id)===Number(r.roster_id)),sx=rows[sidx];return `<tr><td class="rank">${i+1}</td><td><strong>${esc(name(r))}</strong></td><td>${rec(r)}</td><td><span class="playoff-tag ${i<playoffTeams?'in':''}">${i<playoffTeams?'IN':'OUT'}</span></td><td>${sidx>=0?`#${sidx+1}`:'—'}</td><td>${sx?.top3??'—'}</td></tr>`}).join('')}</tbody></table></div><div class="card schedule-note"><strong>How to read this</strong><p class="muted">A contender currently outside the playoff field with an easy remaining schedule may have a better path than its seed suggests. Conversely, a top seed with several top-three power opponents left has less margin for error.</p></div></div>`}
function scheduleView(){setTimeout(()=>{if(!scheduleLoaded&&!scheduleLoading)loadScheduleData()},0);const tabs=[{id:'league',label:'League Schedule'},{id:'sos',label:'Strength of Schedule'},{id:'team',label:'Team Schedule'},{id:'playoffs',label:'Playoff Path'}];let panel=scheduleTab==='sos'?sosPanel():scheduleTab==='team'?teamSchedulePanel():scheduleTab==='playoffs'?playoffPathPanel():leagueSchedulePanel();return `${scheduleSummary()}${innerNav(tabs,scheduleTab,'setScheduleTab')}${panel}`}
const scheduleBaseRender=render;render=function(){if(S.view==='schedule'){$('#pageTitle').textContent='Schedule Center';root.innerHTML=scheduleView();return}scheduleBaseRender()};window.render=render;
