let sportsbookTab='myplayers',sportsbookData=null,sportsbookLoading=false,sportsbookError='',sportsbookOwnerFilter='all';
function setSportsbookTab(id){sportsbookTab=id;render();if(!sportsbookData&&!sportsbookLoading)loadSportsbook()}
window.setSportsbookTab=setSportsbookTab;
function setSportsbookOwnerFilter(v){sportsbookOwnerFilter=String(v||'all');try{localStorage.setItem('leagueHQ.sportsbookOwnerFilter',sportsbookOwnerFilter)}catch{}render()}
window.setSportsbookOwnerFilter=setSportsbookOwnerFilter;
try{sportsbookOwnerFilter=localStorage.getItem('leagueHQ.sportsbookOwnerFilter')||'all'}catch{}
async function loadSportsbook(){sportsbookLoading=true;sportsbookError='';if(S.view==='sportsbook')render();try{const r=await fetch('/api/sportsbook');const d=await r.json();if(!r.ok)throw Error(d.error||'Could not load odds');sportsbookData=d}catch(e){sportsbookError=e.message||'Could not load odds'}finally{sportsbookLoading=false;if(S.view==='sportsbook')render()}}
window.loadSportsbook=loadSportsbook;
function allRosterPlayerNames(){const map=new Map;S.rosters.forEach(r=>(r.players||[]).forEach(id=>map.set((pname(id)||'').toLowerCase(),{id,name:pname(id),roster:r})));return map}
function sportsbookRosterNames(rid){const r=roster(rid);return new Set((r?.players||[]).map(id=>(pname(id)||'').toLowerCase()).filter(Boolean))}
function sportsbookOwnerOptions(){return [...S.rosters].sort((a,b)=>name(a).localeCompare(name(b))).map(r=>`<option value="${r.roster_id}" ${String(sportsbookOwnerFilter)===String(r.roster_id)?'selected':''}>${esc(name(r))}</option>`).join('')}
function sportsbookPlayerFilterBar(){const selected=sportsbookOwnerFilter==='all'?null:roster(Number(sportsbookOwnerFilter)),count=selected?(selected.players||[]).length:null;return `<div class="sportsbook-filter card"><div><div class="eyebrow">PLAYER FILTER</div><strong>${selected?`Showing ${esc(name(selected))}'s players`:'Showing all league players'}</strong><small>${selected?`${count} rostered players · only posted props will appear`:'Choose a fantasy franchise to see only its players across prop tabs.'}</small></div><label><span>Fantasy Team</span><select onchange="setSportsbookOwnerFilter(this.value)"><option value="all" ${sportsbookOwnerFilter==='all'?'selected':''}>All League Players</option>${sportsbookOwnerOptions()}</select></label>${selected?`<button onclick="setSportsbookOwnerFilter('all')">Clear Filter</button>`:''}</div>`}
function bookLabel(k){return({draftkings:'DraftKings',fanduel:'FanDuel',betmgm:'BetMGM',caesars:'Caesars'})[k]||k}
function oddsVal(v){if(v===null||v===undefined||v==='')return'—';const n=Number(v);return Number.isFinite(n)&&n>0?`+${n}`:String(v)}
function statLabel(s=''){return s.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase()).replace('Passing Touchdowns','Pass TDs').replace('Passing Yards','Pass Yards').replace('Receiving Yards','Rec Yards').replace('Rushing Yards','Rush Yards')}
function bestBook(by={}){const rows=Object.entries(by).filter(([,v])=>v?.available!==false&&v?.odds!==null&&v?.odds!==undefined);if(!rows.length)return null;return rows.sort((a,b)=>Number(b[1].odds)-Number(a[1].odds))[0]}
function sportsbookLink(e,b,v){return v?.link||e?.links?.[b]||null}
function propRow(p,e,mode){const best=bestBook(p.byBookmaker),owned=allRosterPlayerNames().get((p.playerName||'').toLowerCase());return `<div class="prop-row"><div class="prop-player"><strong>${esc(p.playerName||'Player')}</strong>${owned?`<span class="fantasy-owner">${esc(name(owned.roster))}</span>`:''}<small>${esc(statLabel(p.statID))} · ${esc((p.side||'').toUpperCase())} ${p.consensusLine??''}</small></div><div class="book-odds-grid">${['draftkings','fanduel','betmgm','caesars'].map(b=>{const v=p.byBookmaker?.[b],link=sportsbookLink(e,b,v);const inner=`<span>${bookLabel(b)}</span><strong>${v?oddsVal(v.odds):'—'}</strong><small>${v?.line??p.consensusLine??''}${link&&v?' · OPEN ↗':''}</small>`;return link&&v?`<a class="book-odd book-link ${best&&best[0]===b?'best-line':''}" href="${esc(link)}" target="_blank" rel="noopener noreferrer">${inner}</a>`:`<div class="book-odd ${best&&best[0]===b?'best-line':''}">${inner}</div>`}).join('')}</div></div>`}
function eventCard(e,props,mode){return `<div class="card sportsbook-event"><div class="sportsbook-event-head"><div><div class="eyebrow">NFL</div><h3>${esc(e.away)} @ ${esc(e.home)}</h3><small class="muted">${e.startTime?new Date(e.startTime).toLocaleString(undefined,{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'Time TBD'}</small></div><span class="badge">${props.length} PROPS</span></div><div class="prop-list">${props.slice(0,30).map(p=>propRow(p,e,mode)).join('')||'<div class="muted empty-state">No matching player props currently posted.</div>'}</div></div>`}
function sportsbookPlayersFilter(mode){const owned=allRosterPlayerNames(),events=sportsbookData?.events||[],selected=sportsbookOwnerFilter==='all'?null:sportsbookRosterNames(Number(sportsbookOwnerFilter));return events.map(e=>{let props=e.props||[];if(mode==='myplayers')props=props.filter(p=>owned.has((p.playerName||'').toLowerCase()));if(mode==='td')props=props.filter(p=>/touchdown|td/i.test(p.statID||'')||/touchdown/i.test(p.marketName||''));if(selected)props=props.filter(p=>selected.has((p.playerName||'').toLowerCase()));return{e,props}}).filter(x=>x.props.length)}
function sportsbookPanel(mode){if(sportsbookLoading)return'<div class="card"><strong>Loading live NFL odds…</strong><p class="muted">Comparing DraftKings, FanDuel, BetMGM and Caesars.</p></div>';if(sportsbookError)return `<div class="card notice"><h3>Sportsbook feed unavailable</h3><p class="muted">${esc(sportsbookError)}</p><button class="save-pref" onclick="loadSportsbook()">Retry</button></div>`;if(!sportsbookData?.configured)return `<div class="card sportsbook-setup"><div class="eyebrow">FEED READY</div><h2>Live odds integration is built</h2><p class="muted">The Sportsbook page is connected to the server-side SportsGameOdds proxy.</p></div>`;if(mode==='games'){return `<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">UPCOMING NFL SLATE</div><h2>Game Lines</h2></div><p class="muted">Player filtering applies to prop tabs. Game lines remain league-wide.</p></div><div class="grid grid-2">${(sportsbookData.events||[]).map(e=>`<div class="card game-line-card"><div class="eyebrow">NFL</div><h3>${esc(e.away)} @ ${esc(e.home)}</h3><p class="muted">${e.startTime?new Date(e.startTime).toLocaleString():''}</p><div class="asset-list">${(e.gameLines||[]).slice(0,8).map(g=>`<span><span>${esc(g.marketName||statLabel(g.statID))}</span><b>${oddsVal(g.consensusOdds)} ${g.consensusLine??''}</b></span>`).join('')||'<span class="muted">Main lines not currently returned for this event.</span>'}</div></div>`).join('')}</div></div>`}const rows=sportsbookPlayersFilter(mode),selected=sportsbookOwnerFilter==='all'?null:roster(Number(sportsbookOwnerFilter));return `<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">LIVE PLAYER MARKETS</div><h2>${mode==='myplayers'?'League Players':mode==='td'?'Touchdown Props':'All Player Props'}</h2></div><p class="muted">${selected?`Filtered to ${esc(name(selected))}. `:mode==='myplayers'?'Fantasy owner is shown under every rostered player. ':''}Best price is highlighted. Click an available sportsbook price to continue there.</p></div><div class="sportsbook-events">${rows.map(x=>eventCard(x.e,x.props,mode)).join('')||`<div class="card muted">${selected?`No posted ${mode==='td'?'touchdown ':''}props currently match ${esc(name(selected))}'s roster.`:'No matching props are posted right now. Lines typically populate closer to kickoff.'}</div>`}</div></div>`}
function sportsbookView(){setTimeout(()=>{if(!sportsbookData&&!sportsbookLoading)loadSportsbook()},0);const tabs=[{id:'myplayers',label:'League Players'},{id:'allprops',label:'All Player Props'},{id:'td',label:'TD Props'},{id:'games',label:'Game Lines'}],filter=sportsbookTab==='games'?'':sportsbookPlayerFilterBar();return `<div class="grid grid-3 section-summary">${card('Books Compared','4','DK · FD · BetMGM · Caesars')}${card('Focus','NFL','Player props + game lines')}${card('Betting','Informational','No wagers on League HQ')}</div>${innerNav(tabs,sportsbookTab,'setSportsbookTab')}${filter}${sportsbookPanel(sportsbookTab)}<div class="attribution">Odds data powered by SportsGameOdds. Prices change at any time. Sportsbook availability and eligibility depend on location and applicable law.</div>`}
const sportsbookBaseRender=render;
render=function(){if(S.view==='sportsbook'){$('#pageTitle').textContent='Sportsbook';root.innerHTML=sportsbookView();return}sportsbookBaseRender()};
window.render=render;
