let standingsTab='current',standingsWeeks=null,standingsLoading=false,standingsError='';
function setStandingsTab(id){standingsTab=id;render();if(!standingsWeeks&&!standingsLoading)loadStandingsHistory()}
window.setStandingsTab=setStandingsTab;
async function loadStandingsHistory(){
  standingsLoading=true;standingsError='';if(S.view==='standings')render();
  try{
    const leg=Number(S.league?.settings?.leg||1),weeks=[];
    const lastCompleted=Math.max(0,leg-1);
    if(lastCompleted>0){const data=await Promise.all(Array.from({length:lastCompleted},(_,i)=>safe(`/league/${LEAGUE}/matchups/${i+1}`,[])));data.forEach((m,i)=>weeks.push({week:i+1,matchups:m||[]}))}
    standingsWeeks=weeks;
  }catch(e){standingsError=e.message||'Could not load season history';standingsWeeks=[]}
  standingsLoading=false;if(S.view==='standings')render();
}
window.loadStandingsHistory=loadStandingsHistory;
function standingAnalytics(){
  const rows=new Map(S.rosters.map(r=>[Number(r.roster_id),{r,actualW:Number(r.settings?.wins||0),actualL:Number(r.settings?.losses||0),actualT:Number(r.settings?.ties||0),pf:Number(r.settings?.fpts||0)+Number(r.settings?.fpts_decimal||0)/100,pa:0,allW:0,allL:0,allT:0,weekly:[],high:null,low:null}]));
  (standingsWeeks||[]).forEach(w=>{
    const scored=w.matchups.filter(m=>rows.has(Number(m.roster_id))).map(m=>({rid:Number(m.roster_id),pts:Number(m.points||0),mid:m.matchup_id}));
    scored.forEach(x=>{const row=rows.get(x.rid);row.weekly.push(x.pts);row.high=row.high===null?x.pts:Math.max(row.high,x.pts);row.low=row.low===null?x.pts:Math.min(row.low,x.pts);const opp=scored.find(y=>y.mid===x.mid&&y.rid!==x.rid);if(opp)row.pa+=opp.pts;scored.forEach(y=>{if(y.rid===x.rid)return;if(x.pts>y.pts)row.allW++;else if(x.pts<y.pts)row.allL++;else row.allT++})})
  });
  const completed=(standingsWeeks||[]).length;
  return [...rows.values()].map(x=>{const allGames=x.allW+x.allL+x.allT,allPct=allGames?(x.allW+x.allT*.5)/allGames:0,expected=allPct*completed,actual=x.actualW+x.actualT*.5;return{...x,completed,allPct,expected,luck:actual-expected,avg:x.weekly.length?x.weekly.reduce((a,b)=>a+b,0)/x.weekly.length:0,maxPF:Number(x.r.settings?.ppts||0)+Number(x.r.settings?.ppts_decimal||0)/100}})
}
function currentStandingsPanel(){const rows=standings();return `<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">OFFICIAL SLEEPER TABLE</div><h2>Current Standings</h2></div><p class="muted">Official record, points scored and dynasty roster value.</p></div><div class="card table-wrap"><table class="table"><thead><tr><th>#</th><th>Franchise</th><th>Record</th><th>PF</th><th>Max PF</th><th>Dynasty Value</th></tr></thead><tbody>${rows.map((r,i)=>`<tr class="clickable" onclick="openTeam(${r.roster_id})"><td class="rank">${i+1}</td><td><strong>${esc(name(r))}</strong></td><td>${rec(r)}</td><td>${pts(r)}</td><td>${(Number(r.settings?.ppts||0)+Number(r.settings?.ppts_decimal||0)/100).toFixed(1)}</td><td>${fmt(rosterValue(r))}</td></tr>`).join('')}</tbody></table></div></div>`}
function noCompletedWeeks(title){return `<div class="card standings-empty"><div class="eyebrow">SEASON ANALYTICS</div><h3>${esc(title)}</h3><p class="muted">This view will populate after the first completed regular-season week. League HQ calculates it from your actual Sleeper weekly scores.</p></div>`}
function allPlayPanel(){if(standingsLoading)return'<div class="card">Loading completed weekly scores…</div>';if(standingsError)return `<div class="card notice">${esc(standingsError)}</div>`;const rows=standingAnalytics();if(!(standingsWeeks||[]).length)return noCompletedWeeks('All-Play Standings are ready');rows.sort((a,b)=>b.allPct-a.allPct||b.pf-a.pf);return `<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">SCHEDULE-INDEPENDENT RECORD</div><h2>All-Play Standings</h2></div><p class="muted">Each week, every team is compared with every other team's score. This removes head-to-head schedule luck.</p></div><div class="card table-wrap"><table class="table"><thead><tr><th>#</th><th>Franchise</th><th>All-Play</th><th>Win %</th><th>Expected Wins</th><th>Actual Wins</th></tr></thead><tbody>${rows.map((x,i)=>`<tr class="clickable" onclick="openTeam(${x.r.roster_id})"><td class="rank">${i+1}</td><td><strong>${esc(name(x.r))}</strong></td><td>${x.allW}-${x.allL}${x.allT?'-'+x.allT:''}</td><td>${(x.allPct*100).toFixed(1)}%</td><td><strong>${x.expected.toFixed(1)}</strong></td><td>${x.actualW}${x.actualT?` + ${x.actualT}T`:''}</td></tr>`).join('')}</tbody></table></div></div>`}
function luckLabel(n){if(n>=1.5)return['Very Lucky','luck-high'];if(n>=.5)return['Lucky','luck-pos'];if(n<=-1.5)return['Very Unlucky','luck-low'];if(n<=-.5)return['Unlucky','luck-neg'];return['Neutral','luck-even']}
function luckPanel(){if(standingsLoading)return'<div class="card">Calculating schedule luck…</div>';const rows=standingAnalytics();if(!(standingsWeeks||[]).length)return noCompletedWeeks('Luck Index is ready');rows.sort((a,b)=>b.luck-a.luck);return `<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">ACTUAL WINS VS EXPECTED WINS</div><h2>Luck Index</h2></div><p class="muted">Positive means a team has won more games than its weekly scoring profile would normally produce; negative means the opposite.</p></div><div class="luck-grid">${rows.map((x,i)=>{const [label,cls]=luckLabel(x.luck);return `<button class="card luck-card" onclick="openTeam(${x.r.roster_id})"><div class="luck-rank">#${i+1}</div><div class="grow"><strong>${esc(name(x.r))}</strong><small>${x.actualW} actual wins · ${x.expected.toFixed(1)} expected</small></div><div class="luck-score ${cls}">${x.luck>=0?'+':''}${x.luck.toFixed(1)}<span>${label}</span></div></button>`}).join('')}</div><div class="card methodology"><h3>How expected wins work</h3><p class="muted">League HQ calculates each team's all-play win percentage across completed weeks, then multiplies that rate by the number of completed weeks. Luck = actual wins (ties count as half) minus expected wins.</p></div></div>`}
function scoringPanel(){if(standingsLoading)return'<div class="card">Loading scoring history…</div>';const rows=standingAnalytics().sort((a,b)=>b.pf-a.pf);return `<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">OFFENSIVE OUTPUT</div><h2>Scoring Leaders</h2></div><p class="muted">Season points plus weekly scoring trends from completed weeks.</p></div><div class="grid grid-3 standings-kpis">${card('Points Leader',rows[0]?name(rows[0].r):'—',rows[0]?`${rows[0].pf.toFixed(1)} PF`:'')}${card('Best Weekly Score',rows.filter(x=>x.high!==null).sort((a,b)=>b.high-a.high)[0]?.high?.toFixed(1)||'—',rows.filter(x=>x.high!==null).sort((a,b)=>b.high-a.high)[0]?name(rows.filter(x=>x.high!==null).sort((a,b)=>b.high-a.high)[0].r):'No completed weeks')}${card('Most Max PF',rows.slice().sort((a,b)=>b.maxPF-a.maxPF)[0]?.maxPF?.toFixed(1)||'—',rows.slice().sort((a,b)=>b.maxPF-a.maxPF)[0]?name(rows.slice().sort((a,b)=>b.maxPF-a.maxPF)[0].r):'')}</div><div class="card table-wrap"><table class="table"><thead><tr><th>#</th><th>Franchise</th><th>PF</th><th>Avg / Week</th><th>High</th><th>Low</th><th>Points Against</th><th>Max PF</th></tr></thead><tbody>${rows.map((x,i)=>`<tr class="clickable" onclick="openTeam(${x.r.roster_id})"><td class="rank">${i+1}</td><td><strong>${esc(name(x.r))}</strong></td><td>${x.pf.toFixed(1)}</td><td>${x.weekly.length?x.avg.toFixed(1):'—'}</td><td>${x.high!==null?x.high.toFixed(1):'—'}</td><td>${x.low!==null?x.low.toFixed(1):'—'}</td><td>${x.weekly.length?x.pa.toFixed(1):'—'}</td><td>${x.maxPF.toFixed(1)}</td></tr>`).join('')}</tbody></table></div></div>`}
function standingsCenterView(){setTimeout(()=>{if(!standingsWeeks&&!standingsLoading)loadStandingsHistory()},0);const tabs=[{id:'current',label:'Current Standings'},{id:'allplay',label:'All-Play Standings'},{id:'luck',label:'Luck Index'},{id:'scoring',label:'Scoring Leaders'}];const rows=standingAnalytics(),completed=(standingsWeeks||[]).length,mostLucky=completed?rows.slice().sort((a,b)=>b.luck-a.luck)[0]:null;let panel=standingsTab==='allplay'?allPlayPanel():standingsTab==='luck'?luckPanel():standingsTab==='scoring'?scoringPanel():currentStandingsPanel();return `<div class="grid grid-3 section-summary">${card('Completed Weeks',completed,'Analytics sample')}${card('Playoff Teams',S.league?.settings?.playoff_teams||'—','Sleeper setting')}${card('Schedule Luck Leader',mostLucky?name(mostLucky.r):'—',mostLucky?`${mostLucky.luck>=0?'+':''}${mostLucky.luck.toFixed(1)} wins`:'After Week 1')}</div>${innerNav(tabs,standingsTab,'setStandingsTab')}${panel}`}
const standingsCenterBaseRender=render;
render=function(){if(S.view==='standings'){$('#pageTitle').textContent='Standings & Analytics';root.innerHTML=standingsCenterView();return}standingsCenterBaseRender()};
window.render=render;
