let tradeTab='history';
let tradeState={two:[null,null],three:[null,null,null],assets:{two:[[],[]],three:[[],[],[]]}};
function setTradeTab(id){tradeTab=id;render();window.scrollTo({top:0,behavior:'smooth'})}
window.setTradeTab=setTradeTab;
function tradeTeamOptions(selected,exclude=[]){return `<option value="">Select franchise…</option>${S.rosters.filter(r=>!exclude.includes(Number(r.roster_id))).map(r=>`<option value="${r.roster_id}" ${Number(selected)===Number(r.roster_id)?'selected':''}>${esc(name(r))}</option>`).join('')}`}
function pickKey(p){return `pick:${p.season}:${p.round}:${p.original}`}
function assetKey(a){return a.type==='player'?`player:${a.id}`:pickKey(a)}
function assetsForTeam(rid){const r=roster(rid);if(!r)return[];const players=(r.players||[]).map(id=>({type:'player',id,label:pname(id),sub:`${player(id).position||'—'} · ${player(id).team||'FA'}`,value:dynastyValue(id)})).sort((a,b)=>b.value-a.value);const picks=ownedPicks(rid).map(p=>({type:'pick',...p,label:`${p.season} Round ${p.round}`,sub:p.original===Number(rid)?'Own pick':`via ${name(roster(p.original))}`,value:pickMarketValue(p)})).sort((a,b)=>a.season-b.season||a.round-b.round);return[...players,...picks]}
function teamAssets(mode,idx){const rid=tradeState[mode][idx];if(!rid)return[];return assetsForTeam(rid)}
function selectedKeys(mode,idx){return new Set((tradeState.assets[mode][idx]||[]).map(assetKey))}
function setTradeTeam(mode,idx,value){tradeState[mode][idx]=value?Number(value):null;tradeState.assets[mode][idx]=[];render()}
window.setTradeTeam=setTradeTeam;
function toggleTradeAsset(mode,idx,key){const pool=teamAssets(mode,idx),a=pool.find(x=>assetKey(x)===key);if(!a)return;const arr=tradeState.assets[mode][idx]||[],found=arr.findIndex(x=>assetKey(x)===key);if(found>=0)arr.splice(found,1);else arr.push(a);tradeState.assets[mode][idx]=arr;render()}
window.toggleTradeAsset=toggleTradeAsset;
function assetValue(a){return Number(a?.value||0)}
function outgoingValue(mode,idx){return(tradeState.assets[mode][idx]||[]).reduce((s,a)=>s+assetValue(a),0)}
function receivedValue(mode,idx){const count=mode==='two'?2:3;let total=0;for(let j=0;j<count;j++){if(j===idx)continue;const arr=tradeState.assets[mode][j]||[];if(mode==='two')total+=arr.reduce((s,a)=>s+assetValue(a),0);else total+=arr.filter(a=>Number(a.to??idx)===idx).reduce((s,a)=>s+assetValue(a),0)}return total}
function fairnessLabel(vals){const populated=vals.filter(v=>v>0);if(populated.length<2)return{label:'Build the trade',className:'neutral',gap:null};const hi=Math.max(...populated),lo=Math.min(...populated),gap=hi?((hi-lo)/hi)*100:0;return gap<=5?{label:'Very Fair',className:'great',gap}:gap<=10?{label:'Fair',className:'good',gap}:gap<=18?{label:'Close',className:'warn',gap}:{label:'Needs Work',className:'bad',gap}}
function assetPicker(mode,idx){const rid=tradeState[mode][idx],keys=selectedKeys(mode,idx),pool=teamAssets(mode,idx);if(!rid)return'<div class="trade-empty">Select a franchise first.</div>';return `<div class="trade-asset-picker">${pool.map(a=>`<button class="trade-asset ${keys.has(assetKey(a))?'selected':''}" onclick="toggleTradeAsset('${mode}',${idx},'${assetKey(a)}')"><div><strong>${esc(a.label)}</strong><small>${esc(a.sub||'')}</small></div><b>${fmt(a.value)}</b></button>`).join('')}</div>`}
function selectedSummary(mode,idx){const arr=tradeState.assets[mode][idx]||[];if(!arr.length)return'<span class="muted">No assets selected</span>';return arr.map(a=>`<span><strong>${esc(a.label)}</strong><b>${fmt(a.value)}</b></span>`).join('')}
function twoTeamCalculator(){const [a,b]=tradeState.two,vals=[outgoingValue('two',0),outgoingValue('two',1)],fair=fairnessLabel(vals);return `<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">LIVE LEAGUE ASSETS</div><h2>2-Team Trade Calculator</h2></div><p class="muted">Pick two franchises, select players and future picks, and compare the current dynasty value moving each way.</p></div><div class="trade-lab-grid two-team">${[0,1].map(i=>`<div class="card trade-builder"><label>Franchise ${i+1}<select class="trade-select" onchange="setTradeTeam('two',${i},this.value)">${tradeTeamOptions(tradeState.two[i],[tradeState.two[1-i]].filter(Boolean))}</select></label><div class="trade-builder-head"><span>Assets sent</span><strong>${fmt(vals[i])}</strong></div>${assetPicker('two',i)}<div class="selected-assets">${selectedSummary('two',i)}</div></div>`).join('')}</div><div class="card trade-verdict"><div><div class="eyebrow">VALUE CHECK</div><h3 class="verdict-${fair.className}">${fair.label}</h3><p class="muted">${fair.gap===null?'Select assets on both sides to calculate fairness.':`The value gap is ${fair.gap.toFixed(1)}% between the two packages.`}</p></div><div class="trade-value-compare"><div><span>${a?esc(name(roster(a))):'Team 1'} sends</span><strong>${fmt(vals[0])}</strong></div><div class="trade-arrow">⇄</div><div><span>${b?esc(name(roster(b))):'Team 2'} sends</span><strong>${fmt(vals[1])}</strong></div></div></div><div class="card methodology"><h3>How to read it</h3><p class="muted">This compares raw current market value. It does not automatically add a premium for consolidating several smaller assets into one elite player, so use the result as a fairness baseline rather than an automatic accept/decline verdict.</p></div>${attribution()}</div>`}
function setThreeDestination(fromIdx,key,toIdx){const arr=tradeState.assets.three[fromIdx]||[],a=arr.find(x=>assetKey(x)===key);if(a)a.to=Number(toIdx);render()}
window.setThreeDestination=setThreeDestination;
function threeSelected(mode,idx){const arr=tradeState.assets.three[idx]||[];if(!arr.length)return'<span class="muted">No assets selected</span>';return arr.map(a=>`<div class="three-selected"><div><strong>${esc(a.label)}</strong><small>${fmt(a.value)}</small></div><label>To<select onchange="setThreeDestination(${idx},'${assetKey(a)}',this.value)">${[0,1,2].filter(x=>x!==idx).map(x=>`<option value="${x}" ${Number(a.to??([0,1,2].find(y=>y!==idx)))===x?'selected':''}>${tradeState.three[x]?esc(name(roster(tradeState.three[x]))):`Team ${x+1}`}</option>`).join('')}</select></label></div>`).join('')}
function threeReceived(idx){let total=0;for(let j=0;j<3;j++){if(j===idx)continue;for(const a of tradeState.assets.three[j]||[]){const defaultTo=[0,1,2].find(x=>x!==j);if(Number(a.to??defaultTo)===idx)total+=assetValue(a)}}return total}
function threeTeamLab(){const selectedTeams=tradeState.three.filter(Boolean);const received=[0,1,2].map(threeReceived),fair=fairnessLabel(received);return `<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">MULTI-TEAM BUILDER</div><h2>3-Team Trade Lab</h2></div><p class="muted">Build a real three-team deal and route each selected player or pick to the franchise that would receive it.</p></div><div class="trade-lab-grid three-team">${[0,1,2].map(i=>`<div class="card trade-builder"><label>Franchise ${i+1}<select class="trade-select" onchange="setTradeTeam('three',${i},this.value)">${tradeTeamOptions(tradeState.three[i],tradeState.three.filter((x,j)=>j!==i&&x).map(Number))}</select></label><div class="trade-builder-head"><span>Select assets to send</span><strong>${fmt(outgoingValue('three',i))}</strong></div>${assetPicker('three',i)}<div class="selected-assets three-assets">${threeSelected('three',i)}</div><div class="received-total"><span>Value received</span><strong>${fmt(received[i])}</strong></div></div>`).join('')}</div><div class="card trade-verdict"><div><div class="eyebrow">3-TEAM BALANCE</div><h3 class="verdict-${fair.className}">${fair.label}</h3><p class="muted">${selectedTeams.length<3?'Select three different franchises to build the full deal.':fair.gap===null?'Route assets to calculate the balance.':`Largest value spread: ${fair.gap.toFixed(1)}%.`}</p></div><div class="three-balance">${[0,1,2].map(i=>`<div><span>${tradeState.three[i]?esc(name(roster(tradeState.three[i]))):`Team ${i+1}`}</span><strong>${fmt(received[i])}</strong><small>received</small></div>`).join('')}</div></div><div class="card methodology"><h3>Three-team trade note</h3><p class="muted">For a multi-team deal, each franchise does not need to send exactly the value it receives from one specific partner. What matters is whether the total package each team receives makes sense for its roster and strategy.</p></div>${attribution()}</div>`}
function completedTradesPanel(){const tx=S.tx.filter(t=>t.type==='trade'&&t.status==='complete');if(!tx.length)return'<div class="card muted">No completed trades have been returned for the current league season.</div>';return `<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">SLEEPER TRANSACTION HISTORY</div><h2>Completed Trades</h2></div><p class="muted">Current dynasty values are shown next to players in each completed deal.</p></div><div class="trade-list">${tx.map(t=>`<div class="card trade-card"><div class="trade-head"><strong>${date(t.created)}</strong><span class="badge">TRADE</span></div><div class="trade-sides">${(t.roster_ids||[]).map(rid=>`<div class="trade-side"><button onclick="openTeam(${rid})">${esc(name(roster(rid)))}</button><div class="asset-list">${tradeAssetLines(t,rid)}</div></div>`).join('')}</div></div>`).join('')}</div>${attribution()}</div>`}
function tradeCenterView(){const tabs=[{id:'history',label:'Completed Trades'},{id:'calculator',label:'2-Team Calculator'},{id:'three',label:'3-Team Trade Lab'}];const panel=tradeTab==='calculator'?twoTeamCalculator():tradeTab==='three'?threeTeamLab():completedTradesPanel();return `<div class="grid grid-3 section-summary">${card('Completed Trades',S.tx.filter(t=>t.type==='trade'&&t.status==='complete').length,'Current season')}${card('Value Format',currentFormat(),'Live dynasty market')}${card('Trade Tools','2 + 3 Team','Actual league assets')}</div>${innerNav(tabs,tradeTab,'setTradeTab')}${panel}`}
const tradeCenterBaseRender=render;
render=function(){if(S.view==='trades'){$('#pageTitle').textContent='Trade Center';root.innerHTML=tradeCenterView();return}tradeCenterBaseRender()};
window.render=render;
