let finderTab='needs';
function setFinderTab(id){finderTab=id;render();window.scrollTo({top:0,behavior:'smooth'})}
window.setFinderTab=setFinderTab;
function teamProfile(r){const row=outlookRows().find(x=>Number(x.r.roster_id)===Number(r.roster_id));const pos=['QB','RB','WR','TE'].map(p=>({pos:p,value:positionValue(r,p)}));const avg={};for(const p of pos)avg[p.pos]=S.rosters.reduce((a,x)=>a+positionValue(x,p.pos),0)/Math.max(S.rosters.length,1);const needs=pos.filter(x=>x.value<avg[x.pos]*.82).sort((a,b)=>(a.value/avg[a.pos])-(b.value/avg[b.pos]));const surplus=pos.filter(x=>x.value>avg[x.pos]*1.18).sort((a,b)=>(b.value/avg[b.pos])-(a.value/avg[a.pos]));const assets=(r.players||[]).map(id=>({id:String(id),name:pname(id),pos:player(id).position,age:Number(player(id).age||0),value:dynastyValue(String(id))})).filter(x=>x.value>0).sort((a,b)=>b.value-a.value);let wants=[];if(row?.label==='Win Now'||row?.label==='Dynasty Powerhouse')wants=['Elite starters','Depth for playoff push'];else if(row?.label==='Rebuild'||row?.label==='Retooling')wants=['2027+ draft picks','Young ascending players'];else wants=['Value-neutral upgrades','Roster consolidation'];needs.slice(0,2).forEach(x=>wants.push(x.pos+' help'));let sells=[];surplus.slice(0,2).forEach(x=>sells.push(x.pos+' depth'));if(row?.label==='Rebuild'||row?.label==='Retooling')assets.filter(x=>x.age>=28).slice(0,2).forEach(x=>sells.push(x.name));if((row?.label==='Win Now'||row?.label==='Dynasty Powerhouse')&&draftCapitalValue(r.roster_id)>0)sells.push('Future picks for proven help');return{r,row,needs,surplus,assets,wants:[...new Set(wants)],sells:[...new Set(sells)]}}
function allProfiles(){return S.rosters.map(teamProfile)}
function needScore(a,b){let score=0,reasons=[];for(const n of a.needs){const s=b.surplus.find(x=>x.pos===n.pos);if(s){score+=30;reasons.push(`${a.r?name(a.r):''} needs ${n.pos}; ${name(b.r)} is strong there`)}}for(const n of b.needs){const s=a.surplus.find(x=>x.pos===n.pos);if(s){score+=30;reasons.push(`${name(b.r)} needs ${n.pos}; ${name(a.r)} is strong there`)}}if(a.row&&b.row&&a.row.label!==b.row.label){const winA=/Win Now|Powerhouse/.test(a.row.label),rebB=/Rebuild|Retooling/.test(b.row.label),winB=/Win Now|Powerhouse/.test(b.row.label),rebA=/Rebuild|Retooling/.test(a.row.label);if((winA&&rebB)||(winB&&rebA)){score+=25;reasons.push('Their competitive windows complement each other')}}const pickDiff=Math.abs(draftCapitalValue(a.r.roster_id)-draftCapitalValue(b.r.roster_id));if(pickDiff>500){score+=10;reasons.push('Different draft-capital profiles create flexibility')}return{score,reasons}}
function matches(){const p=allProfiles(),out=[];for(let i=0;i<p.length;i++)for(let j=i+1;j<p.length;j++){const s=needScore(p[i],p[j]);out.push({a:p[i],b:p[j],...s})}return out.sort((x,y)=>y.score-x.score)}
function openFinderTrade(a,b){tradeState.two=[Number(a),Number(b)];tradeState.assets.two=[[],[]];tradeTab='calculator';S.view='trades';document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view==='trades'));render();window.scrollTo({top:0,behavior:'smooth'})}
window.openFinderTrade=openFinderTrade;
function needsPanel(){return `<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">ROSTER CONSTRUCTION</div><h2>League Needs Board</h2></div><p class="muted">Automatically inferred from positional value, team window and draft capital.</p></div><div class="finder-grid">${allProfiles().map(x=>`<div class="card finder-card"><div class="trade-head"><div><div class="eyebrow">${esc(x.row?.label||'TEAM')}</div><h3>${esc(name(x.r))}</h3></div><button class="finder-open" onclick="openTeam(${x.r.roster_id})">Team →</button></div><div class="finder-cols"><div><small>LIKELY BUYING</small>${x.wants.map(v=>`<span class="need-chip">${esc(v)}</span>`).join('')}</div><div><small>POSSIBLE SELLING</small>${x.sells.length?x.sells.map(v=>`<span class="sell-chip">${esc(v)}</span>`).join(''):'<span class="muted">No obvious surplus</span>'}</div></div></div>`).join('')}</div></div>`}
function matchesPanel(){const rows=matches().slice(0,12);return `<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">TRADE FIT</div><h2>Best Natural Trade Matches</h2></div><p class="muted">Higher scores mean the two rosters have more complementary needs, surpluses and competitive windows.</p></div><div class="finder-grid">${rows.map((x,i)=>`<div class="card match-card"><div class="match-score">#${i+1}<b>${x.score}</b></div><div class="match-teams"><strong>${esc(name(x.a.r))}</strong><span>⇄</span><strong>${esc(name(x.b.r))}</strong></div><div class="match-reasons">${x.reasons.slice(0,3).map(r=>`<span>${esc(r)}</span>`).join('')}</div><button class="save-pref" onclick="openFinderTrade(${x.a.r.roster_id},${x.b.r.roster_id})">Open in Trade Calculator →</button></div>`).join('')}</div></div>`}
function targetsPanel(){const profiles=allProfiles();return `<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">ASSET DISCOVERY</div><h2>Potentially Available Targets</h2></div><p class="muted">Players are surfaced when they sit in a positional surplus or may not match their team's competitive window.</p></div><div class="card table-wrap"><table class="table"><thead><tr><th>Player</th><th>Owner</th><th>Pos</th><th>Age</th><th>Value</th><th>Why It Fits</th></tr></thead><tbody>${profiles.flatMap(x=>x.assets.filter(a=>x.surplus.some(s=>s.pos===a.pos)||(x.row?.label==='Rebuild'&&a.age>=28)).slice(0,4).map(a=>({x,a}))).sort((u,v)=>v.a.value-u.a.value).slice(0,40).map(({x,a})=>`<tr class="clickable" onclick="openPlayer('${a.id}','finder')"><td><strong>${esc(a.name)}</strong></td><td>${esc(name(x.r))}</td><td>${esc(a.pos||'—')}</td><td>${a.age||'—'}</td><td>${fmt(a.value)}</td><td>${x.row?.label==='Rebuild'&&a.age>=28?'Veteran on a rebuilding roster':`${a.pos} surplus`}</td></tr>`).join('')}</tbody></table></div></div>`}
function finderView(){const m=matches()[0];const tabs=[{id:'needs',label:'League Needs'},{id:'matches',label:'Best Matches'},{id:'targets',label:'Potential Targets'}];const panel=finderTab==='matches'?matchesPanel():finderTab==='targets'?targetsPanel():needsPanel();return `<div class="grid grid-3 section-summary">${card('Best Match',m?`${name(m.a.r)} ↔ ${name(m.b.r)}`:'—',m?`Fit score ${m.score}`:'')}${card('Teams Analyzed',S.rosters.length,'Live Sleeper rosters')}${card('Model Inputs','Needs + Window','Position strength · age · picks')}</div>${innerNav(tabs,finderTab,'setFinderTab')}${panel}<div class="card methodology"><h3>Important</h3><p class="muted">This is a trade-discovery model, not a claim that an owner actually wants to move a player. It identifies plausible conversations from roster construction; use the Trade Calculator to value a specific offer.</p></div>${attribution()}`}
const finderBaseRender=render;render=function(){if(S.view==='finder'){$('#pageTitle').textContent='Trade Block & Needs';root.innerHTML=finderView();return}finderBaseRender()};window.render=render;
