let sectionTabs={draft:'capital',values:'rankings',team:'roster'};
let selectedDraftId=null;
function innerNav(items,active,handler){return `<div class="inner-tabs" role="tablist">${items.map(x=>`<button class="inner-tab ${x.id===active?'active':''}" onclick="${handler}('${x.id}')">${x.label}</button>`).join('')}</div>`}
function setDraftTab(id){sectionTabs.draft=id;render();window.scrollTo({top:0,behavior:'smooth'})}
function setValuesTab(id){sectionTabs.values=id;render();window.scrollTo({top:0,behavior:'smooth'})}
function setTeamTab(id){sectionTabs.team=id;render();window.scrollTo({top:0,behavior:'smooth'})}
function setDraftSeason(id){selectedDraftId=id;render();window.scrollTo({top:0,behavior:'smooth'})}
window.setDraftTab=setDraftTab;window.setValuesTab=setValuesTab;window.setTeamTab=setTeamTab;window.setDraftSeason=setDraftSeason;

function draftCapitalPanel(){return `<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">CURRENT OWNERSHIP</div><h2>Future Draft Capital</h2></div><p class="muted">Every future pick currently controlled by each franchise, with dynasty value estimates.</p></div><div class="grid grid-2">${powerRankings().map(x=>`<div class="card"><button class="team-title" onclick="openTeam(${x.r.roster_id})">${esc(name(x.r))} · ${fmt(x.picks)}</button>${picksHtml(x.r.roster_id)}</div>`).join('')}</div></div>`}
function draftHistoryPanel(){const boards=S.draftBoards.filter(x=>(x.picks||[]).length);if(!boards.length)return '<div class="card muted">No completed draft boards found.</div>';if(!selectedDraftId||!boards.some(x=>String(x.draft.draft_id)===String(selectedDraftId)))selectedDraftId=boards[0].draft.draft_id;const current=boards.find(x=>String(x.draft.draft_id)===String(selectedDraftId))||boards[0];return `<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">RETROSPECTIVE ANALYSIS</div><h2>Draft History & Grades</h2></div><p class="muted">Choose a draft below to see the full board and who has gained the most value since draft day.</p></div><div class="season-tabs">${boards.map(b=>`<button class="season-tab ${String(b.draft.draft_id)===String(selectedDraftId)?'active':''}" onclick="setDraftSeason('${b.draft.draft_id}')">${esc(b.draft.season||'Draft')}</button>`).join('')}</div>${draftBoard(current)}</div>`}
function prospectPanel(){setTimeout(()=>loadProspectNews(selectedProspect),0);return `<div class="section-panel">${prospectHubHtml()}</div>`}

draft=function(){const complete=S.draftBoards.filter(x=>x.draft.status==='complete'&&(x.picks||[]).length),latest=complete[0],winner=latest?draftGrades(latest)[0]:null;const tabs=[{id:'capital',label:'Future Draft Capital'},{id:'history',label:'Draft History & Grades'},{id:'prospects',label:'2027 Prospect Hub'}];let panel=sectionTabs.draft==='history'?draftHistoryPanel():sectionTabs.draft==='prospects'?prospectPanel():draftCapitalPanel();return `<div class="grid grid-4 section-summary">${card('Drafts Found',S.draftBoards.length,'Current + historical')}${card('Latest Draft Winner',winner?name(roster(winner.rid)):'—',latest?`${latest.draft.season} retrospective`:'No completed draft')}${card('Future Pick Value',fmt(S.rosters.reduce((a,r)=>a+draftCapitalValue(r.roster_id),0)),'League-wide capital')}${card('Value Format',currentFormat(),'RosterAudit market')}</div>${innerNav(tabs,sectionTabs.draft,'setDraftTab')}${panel}${attribution()}`}

function valueRankingPanel(){const ranks=(S.rankings.length?S.rankings:Object.keys(S.values).map(id=>({sleeper_id:id,name:pname(id),position:player(id).position,team:player(id).team,value:dynastyValue(id)}))).map(x=>({...x,_id:String(x.sleeper_id||x.player_id||x.id||''),_value:Number(x.value||x.val_sf||x.val_1qb||dynastyValue(String(x.sleeper_id||x.player_id||x.id||'')))||0})).sort((a,b)=>b._value-a._value).slice(0,100);return `<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">CURRENT MARKET</div><h2>Dynasty Rankings</h2></div><p class="muted">Search the top dynasty assets in the format automatically detected from your league.</p></div><div class="card search-card"><input id="valueSearch" class="search-input" placeholder="Search player, position or NFL team…" oninput="filterValues()"></div><div class="card table-wrap"><table class="table value-table"><thead><tr><th>#</th><th>Player</th><th>Pos</th><th>NFL</th><th>Value</th></tr></thead><tbody id="valueRows">${ranks.map((x,i)=>`<tr data-search="${esc(`${x.name||pname(x._id)} ${x.position||player(x._id).position} ${x.team||player(x._id).team}`.toLowerCase())}"><td class="rank">${i+1}</td><td><strong>${esc(x.name||pname(x._id))}</strong></td><td>${esc(x.position||player(x._id).position||'—')}</td><td>${esc(x.team||player(x._id).team||'FA')}</td><td><strong>${fmt(x._value)}</strong></td></tr>`).join('')}</tbody></table></div></div>`}
function valueMoversPanel(){return `<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">MARKET MOVEMENT</div><h2>Dynasty Stock Watch</h2></div><p class="muted">Players making the biggest moves in the live dynasty market.</p></div>${S.movers.length?`<div class="grid grid-2">${S.movers.slice(0,20).map(m=>`<div class="card mover"><div><strong>${esc(m.name||pname(String(m.sleeper_id||m.player_id||'')))}</strong><div class="muted">${esc(m.position||'')} ${esc(m.team||'')}</div></div><div class="metric-small ${Number(m.trend_7d||m.change||0)>=0?'up':'down'}">${Number(m.trend_7d||m.change||0)>=0?'+':''}${fmt(m.trend_7d||m.change||0)}</div></div>`).join('')}</div>`:'<div class="card muted">Market mover data is temporarily unavailable.</div>'}</div>`}
values=function(){const tabs=[{id:'rankings',label:'Dynasty Rankings'},{id:'movers',label:'Market Movers'}];const panel=sectionTabs.values==='movers'?valueMoversPanel():valueRankingPanel();return `<div class="grid grid-3 section-summary">${card('Scoring Format',currentFormat(),`${S.rosters.length}-team league`)}${card('Players Valued',Object.keys(S.values).length,'Live market lookup')}${card('Value Source','RosterAudit','Trade-derived dynasty market')}</div>${innerNav(tabs,sectionTabs.values,'setValuesTab')}${panel}${attribution()}`}

teamDetail=function(id){const r=roster(id);if(!r)return teams();const ids=[...(r.players||[])].sort((a,b)=>dynastyValue(b)-dynastyValue(a));const tabs=[{id:'roster',label:'Roster'},{id:'capital',label:'Draft Capital'}];const rosterPanel=`<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">VALUE SORTED</div><h2>Roster</h2></div><p class="muted">Current Sleeper roster ordered by dynasty market value.</p></div><div class="card table-wrap"><table class="table"><thead><tr><th>Pos</th><th>Player</th><th>NFL</th><th>Value</th><th>Status</th></tr></thead><tbody>${rosterRows(ids,r)}</tbody></table></div></div>`;const capitalPanel=`<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">FUTURE ASSETS</div><h2>Draft Capital</h2></div><p class="muted">Current future pick ownership and estimated dynasty value.</p></div><div class="card">${picksHtml(id)}</div></div>`;return `<button class="back-btn" onclick="go('teams')">← All Teams</button><div class="team-hero card">${teamLogo(r)}<div><div class="eyebrow">FRANCHISE</div><h2>${esc(name(r))}</h2><div class="muted">${rec(r)} · ${fmt(rosterValue(r))} roster value · ${fmt(draftCapitalValue(id))} draft capital</div></div></div><div class="grid grid-3 value-summary section-summary">${card('Roster Value',fmt(rosterValue(r)),currentFormat())}${card('Starter Value',fmt(starterValue(r)),'Current Sleeper starters')}${card('Draft Capital',fmt(draftCapitalValue(id)),'Mid-pick estimate')}</div>${innerNav(tabs,sectionTabs.team,'setTeamTab')}${sectionTabs.team==='capital'?capitalPanel:rosterPanel}${attribution()}`}

const originalGo=go;
go=function(v){if(v!=='teams')sectionTabs.team='roster';originalGo(v)};
window.go=go;
const originalOpenTeam=openTeam;
openTeam=function(id){sectionTabs.team='roster';originalOpenTeam(id)};
window.openTeam=openTeam;
