let waiverTab='targets';
function setWaiverTab(id){waiverTab=id;render();window.scrollTo({top:0,behavior:'smooth'})}window.setWaiverTab=setWaiverTab;
function rosteredIds(){const s=new Set;S.rosters.forEach(r=>(r.players||[]).forEach(id=>s.add(String(id))));return s}
function rankRows(){return(S.rankings||[]).map(x=>{const id=String(x.sleeper_id||x.player_id||x.id||''),p=player(id);return{id,name:x.name||pname(id),pos:x.position||p.position||'—',team:x.team||p.team||'FA',value:Number(x.value||x.val_sf||x.val_1qb||dynastyValue(id))||0}}).filter(x=>x.id)}
function freeAgents(){const owned=rosteredIds(),rows=rankRows().filter(x=>!owned.has(x.id)&&!['DEF','K'].includes(x.pos));if(rows.length)return rows.sort((a,b)=>b.value-a.value);return Object.keys(S.players).filter(id=>!owned.has(String(id))).map(id=>({id:String(id),name:pname(id),pos:player(id).position||'—',team:player(id).team||'FA',value:dynastyValue(String(id))})).filter(x=>x.value>0&&!['DEF','K'].includes(x.pos)).sort((a,b)=>b.value-a.value)}
function trendMap(){const m=new Map;(S.movers||[]).forEach(x=>{const id=String(x.sleeper_id||x.player_id||x.id||'');if(id)m.set(id,Number(x.trend_7d||x.change||0)||0)});return m}
function waiverRows(filter='all'){const trend=trendMap();let rows=freeAgents().map(x=>({...x,trend:trend.get(x.id)||0}));if(filter!=='all')rows=rows.filter(x=>x.pos===filter);return rows.slice(0,60)}
function waiverTable(rows){return `<div class="card table-wrap"><table class="table"><thead><tr><th>#</th><th>Pos</th><th>Player</th><th>NFL</th><th>Dynasty Value</th><th>7d Move</th><th>Availability</th></tr></thead><tbody>${rows.map((x,i)=>`<tr><td class="rank">${i+1}</td><td><span class="${posClass(x.pos)}">${esc(x.pos)}</span></td><td><strong>${esc(x.name)}</strong></td><td>${esc(x.team||'FA')}</td><td><strong>${fmt(x.value)}</strong></td><td class="${x.trend>0?'trend-up':x.trend<0?'trend-down':''}">${x.trend>0?'+':''}${fmt(x.trend)}</td><td><span class="role">FREE AGENT</span></td></tr>`).join('')||'<tr><td colspan="7" class="muted">No ranked free agents found.</td></tr>'}</tbody></table></div>`}
function targetsPanel(){const rows=waiverRows();return `<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">AVAILABLE IN YOUR LEAGUE</div><h2>Best Dynasty Free Agents</h2></div><p class="muted">Cross-checks current Sleeper rosters against the same dynasty market values used throughout League HQ.</p></div>${waiverTable(rows)}</div>`}
function byPositionPanel(){const positions=['QB','RB','WR','TE'];return `<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">POSITIONAL WATCHLIST</div><h2>Best Available by Position</h2></div></div><div class="grid grid-2">${positions.map(pos=>{const rows=waiverRows(pos).slice(0,10);return `<div class="card waiver-pos-card"><div class="waiver-pos-head"><span class="${posClass(pos)}">${pos}</span><strong>Top Available ${pos}s</strong></div><div class="asset-list">${rows.map((x,i)=>`<span><span>${i+1}. ${esc(x.name)} <small class="muted">${esc(x.team||'FA')}</small></span><b>${fmt(x.value)}</b></span>`).join('')||'<span class="muted">No valued free agents.</span>'}</div></div>`}).join('')}</div></div>`}
function risersPanel(){const rows=waiverRows().filter(x=>x.trend!==0).sort((a,b)=>b.trend-a.trend);return `<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">MARKET MOVEMENT</div><h2>Unrostered Risers & Fallers</h2></div><p class="muted">Useful for spotting dynasty adds before the rest of the league reacts.</p></div>${waiverTable(rows)}</div>`}
function rosterNeeds(){const pr=powerRankings();return `<div class="section-panel"><div class="panel-heading"><div><div class="eyebrow">LEAGUE DEPTH MAP</div><h2>Roster Needs</h2></div><p class="muted">Counts rostered QB/RB/WR/TE assets so you can see where each franchise may be shopping.</p></div><div class="card table-wrap"><table class="table"><thead><tr><th>Franchise</th><th>QB</th><th>RB</th><th>WR</th><th>TE</th><th>Roster Value</th></tr></thead><tbody>${pr.map(x=>{const c={QB:0,RB:0,WR:0,TE:0};(x.r.players||[]).forEach(id=>{const p=player(id).position;if(c[p]!==undefined)c[p]++});return `<tr class="clickable" onclick="openTeam(${x.r.roster_id})"><td><strong>${esc(name(x.r))}</strong></td><td>${c.QB}</td><td>${c.RB}</td><td>${c.WR}</td><td>${c.TE}</td><td>${fmt(x.players)}</td></tr>`}).join('')}</tbody></table></div></div>`}
function waiverView(){const free=freeAgents(),top=free[0],tabs=[{id:'targets',label:'Top Targets'},{id:'position',label:'By Position'},{id:'risers',label:'Risers & Fallers'},{id:'needs',label:'Roster Needs'}];let panel=waiverTab==='position'?byPositionPanel():waiverTab==='risers'?risersPanel():waiverTab==='needs'?rosterNeeds():targetsPanel();return `<div class="grid grid-3 section-summary">${card('Ranked Free Agents',free.length,'Not rostered in Sleeper')}${card('Top Available',top?top.name:'—',top?`${top.pos} · ${fmt(top.value)} value`:'')}${card('Market','Dynasty','Live value cross-check')}</div>${innerNav(tabs,waiverTab,'setWaiverTab')}${panel}${attribution()}`}
const waiverBaseRender=render;render=function(){if(S.view==='waivers'){$('#pageTitle').textContent='Waiver Wire';root.innerHTML=waiverView();return}waiverBaseRender()};window.render=render;